var namespacertt_1_1ai_1_1stp_1_1evaluation =
[
    [ "BaseEvaluation", "d1/d1a/classrtt_1_1ai_1_1stp_1_1evaluation_1_1BaseEvaluation.html", "d1/d1a/classrtt_1_1ai_1_1stp_1_1evaluation_1_1BaseEvaluation" ],
    [ "BallPlacementThemGameStateEvaluation", "dc/d07/classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallPlacementThemGameStateEvaluation.html", "dc/d07/classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallPlacementThemGameStateEvaluation" ],
    [ "BallPlacementUsGameStateEvaluation", "d7/db7/classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallPlacementUsGameStateEvaluation.html", "d7/db7/classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallPlacementUsGameStateEvaluation" ],
    [ "FreeKickThemGameStateEvaluation", "d5/df9/classrtt_1_1ai_1_1stp_1_1evaluation_1_1FreeKickThemGameStateEvaluation.html", "d5/df9/classrtt_1_1ai_1_1stp_1_1evaluation_1_1FreeKickThemGameStateEvaluation" ],
    [ "FreeKickUsGameStateEvaluation", "d6/dca/classrtt_1_1ai_1_1stp_1_1evaluation_1_1FreeKickUsGameStateEvaluation.html", "d6/dca/classrtt_1_1ai_1_1stp_1_1evaluation_1_1FreeKickUsGameStateEvaluation" ],
    [ "HaltGameStateEvaluation", "db/d55/classrtt_1_1ai_1_1stp_1_1evaluation_1_1HaltGameStateEvaluation.html", "db/d55/classrtt_1_1ai_1_1stp_1_1evaluation_1_1HaltGameStateEvaluation" ],
    [ "KickOffThemGameStateEvaluation", "d0/d0b/classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffThemGameStateEvaluation.html", "d0/d0b/classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffThemGameStateEvaluation" ],
    [ "KickOffThemPrepareGameStateEvaluation", "db/d78/classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffThemPrepareGameStateEvaluation.html", "db/d78/classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffThemPrepareGameStateEvaluation" ],
    [ "KickOffUsGameStateEvaluation", "d2/ddf/classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffUsGameStateEvaluation.html", "d2/ddf/classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffUsGameStateEvaluation" ],
    [ "KickOffUsOrNormalGameStateEvaluation", "d2/da7/classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffUsOrNormalGameStateEvaluation.html", "d2/da7/classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffUsOrNormalGameStateEvaluation" ],
    [ "KickOffUsPrepareGameStateEvaluation", "dd/db8/classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffUsPrepareGameStateEvaluation.html", "dd/db8/classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffUsPrepareGameStateEvaluation" ],
    [ "NormalOrFreeKickUsGameStateEvaluation", "de/dd9/classrtt_1_1ai_1_1stp_1_1evaluation_1_1NormalOrFreeKickUsGameStateEvaluation.html", "de/dd9/classrtt_1_1ai_1_1stp_1_1evaluation_1_1NormalOrFreeKickUsGameStateEvaluation" ],
    [ "NormalPlayGameStateEvaluation", "d1/d22/classrtt_1_1ai_1_1stp_1_1evaluation_1_1NormalPlayGameStateEvaluation.html", "d1/d22/classrtt_1_1ai_1_1stp_1_1evaluation_1_1NormalPlayGameStateEvaluation" ],
    [ "PenaltyThemGameStateEvaluation", "d8/d60/classrtt_1_1ai_1_1stp_1_1evaluation_1_1PenaltyThemGameStateEvaluation.html", "d8/d60/classrtt_1_1ai_1_1stp_1_1evaluation_1_1PenaltyThemGameStateEvaluation" ],
    [ "PenaltyThemPrepareGameStateEvaluation", "d2/d1d/classrtt_1_1ai_1_1stp_1_1evaluation_1_1PenaltyThemPrepareGameStateEvaluation.html", "d2/d1d/classrtt_1_1ai_1_1stp_1_1evaluation_1_1PenaltyThemPrepareGameStateEvaluation" ],
    [ "PenaltyUsGameStateEvaluation", "de/d02/classrtt_1_1ai_1_1stp_1_1evaluation_1_1PenaltyUsGameStateEvaluation.html", "de/d02/classrtt_1_1ai_1_1stp_1_1evaluation_1_1PenaltyUsGameStateEvaluation" ],
    [ "PenaltyUsPrepareGameStateEvaluation", "dc/dc0/classrtt_1_1ai_1_1stp_1_1evaluation_1_1PenaltyUsPrepareGameStateEvaluation.html", "dc/dc0/classrtt_1_1ai_1_1stp_1_1evaluation_1_1PenaltyUsPrepareGameStateEvaluation" ],
    [ "StopGameStateEvaluation", "dd/d4b/classrtt_1_1ai_1_1stp_1_1evaluation_1_1StopGameStateEvaluation.html", "dd/d4b/classrtt_1_1ai_1_1stp_1_1evaluation_1_1StopGameStateEvaluation" ],
    [ "TimeOutGameStateEvaluation", "d9/d4d/classrtt_1_1ai_1_1stp_1_1evaluation_1_1TimeOutGameStateEvaluation.html", "d9/d4d/classrtt_1_1ai_1_1stp_1_1evaluation_1_1TimeOutGameStateEvaluation" ],
    [ "BallInOurDefenseAreaAndStillGlobalEvaluation", "dc/d00/classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallInOurDefenseAreaAndStillGlobalEvaluation.html", "dc/d00/classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallInOurDefenseAreaAndStillGlobalEvaluation" ],
    [ "BallNotInOurDefenseAreaAndStillGlobalEvaluation", "db/db6/classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallNotInOurDefenseAreaAndStillGlobalEvaluation.html", "db/db6/classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallNotInOurDefenseAreaAndStillGlobalEvaluation" ],
    [ "BallOnOurSideGlobalEvaluation", "d9/d25/classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallOnOurSideGlobalEvaluation.html", "d9/d25/classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallOnOurSideGlobalEvaluation" ],
    [ "BallOnTheirSideGlobalEvaluation", "db/df9/classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallOnTheirSideGlobalEvaluation.html", "db/df9/classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallOnTheirSideGlobalEvaluation" ],
    [ "TheyDoNotHaveBallGlobalEvaluation", "db/dbe/classrtt_1_1ai_1_1stp_1_1evaluation_1_1TheyDoNotHaveBallGlobalEvaluation.html", "db/dbe/classrtt_1_1ai_1_1stp_1_1evaluation_1_1TheyDoNotHaveBallGlobalEvaluation" ],
    [ "TheyHaveBallGlobalEvaluation", "da/d0e/classrtt_1_1ai_1_1stp_1_1evaluation_1_1TheyHaveBallGlobalEvaluation.html", "da/d0e/classrtt_1_1ai_1_1stp_1_1evaluation_1_1TheyHaveBallGlobalEvaluation" ],
    [ "WeDoNotHaveBallGlobalEvaluation", "da/d8e/classrtt_1_1ai_1_1stp_1_1evaluation_1_1WeDoNotHaveBallGlobalEvaluation.html", "da/d8e/classrtt_1_1ai_1_1stp_1_1evaluation_1_1WeDoNotHaveBallGlobalEvaluation" ],
    [ "WeHaveBallGlobalEvaluation", "d5/d80/classrtt_1_1ai_1_1stp_1_1evaluation_1_1WeHaveBallGlobalEvaluation.html", "d5/d80/classrtt_1_1ai_1_1stp_1_1evaluation_1_1WeHaveBallGlobalEvaluation" ],
    [ "GoalShotEvaluation", "d3/df8/classrtt_1_1ai_1_1stp_1_1evaluation_1_1GoalShotEvaluation.html", "d3/df8/classrtt_1_1ai_1_1stp_1_1evaluation_1_1GoalShotEvaluation" ],
    [ "LineOfSightEvaluation", "da/dbd/classrtt_1_1ai_1_1stp_1_1evaluation_1_1LineOfSightEvaluation.html", "da/dbd/classrtt_1_1ai_1_1stp_1_1evaluation_1_1LineOfSightEvaluation" ],
    [ "OpennessEvaluation", "d6/d61/classrtt_1_1ai_1_1stp_1_1evaluation_1_1OpennessEvaluation.html", "d6/d61/classrtt_1_1ai_1_1stp_1_1evaluation_1_1OpennessEvaluation" ]
];