// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ActionCommand.proto

#include "ActionCommand.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR ActionCommand::ActionCommand(
    ::_pbi::ConstantInitialized)
  : numrobots_()
  , _numrobots_cached_byte_size_(0){}
struct ActionCommandDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ActionCommandDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ActionCommandDefaultTypeInternal() {}
  union {
    ActionCommand _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ActionCommandDefaultTypeInternal _ActionCommand_default_instance_;
static ::_pb::Metadata file_level_metadata_ActionCommand_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_ActionCommand_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ActionCommand_2eproto = nullptr;

const uint32_t TableStruct_ActionCommand_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ActionCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ActionCommand, numrobots_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ActionCommand)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_ActionCommand_default_instance_._instance,
};

const char descriptor_table_protodef_ActionCommand_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023ActionCommand.proto\"\"\n\rActionCommand\022\021"
  "\n\tnumRobots\030\001 \003(\005b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_ActionCommand_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ActionCommand_2eproto = {
    false, false, 65, descriptor_table_protodef_ActionCommand_2eproto,
    "ActionCommand.proto",
    &descriptor_table_ActionCommand_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_ActionCommand_2eproto::offsets,
    file_level_metadata_ActionCommand_2eproto, file_level_enum_descriptors_ActionCommand_2eproto,
    file_level_service_descriptors_ActionCommand_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ActionCommand_2eproto_getter() {
  return &descriptor_table_ActionCommand_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ActionCommand_2eproto(&descriptor_table_ActionCommand_2eproto);

// ===================================================================

class ActionCommand::_Internal {
 public:
};

ActionCommand::ActionCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  numrobots_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:ActionCommand)
}
ActionCommand::ActionCommand(const ActionCommand& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      numrobots_(from.numrobots_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ActionCommand)
}

inline void ActionCommand::SharedCtor() {
}

ActionCommand::~ActionCommand() {
  // @@protoc_insertion_point(destructor:ActionCommand)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ActionCommand::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ActionCommand::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ActionCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:ActionCommand)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  numrobots_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ActionCommand::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated int32 numRobots = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_numrobots(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 8) {
          _internal_add_numrobots(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ActionCommand::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ActionCommand)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 numRobots = 1;
  {
    int byte_size = _numrobots_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          1, _internal_numrobots(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ActionCommand)
  return target;
}

size_t ActionCommand::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ActionCommand)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 numRobots = 1;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->numrobots_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _numrobots_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ActionCommand::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ActionCommand::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ActionCommand::GetClassData() const { return &_class_data_; }

void ActionCommand::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ActionCommand *>(to)->MergeFrom(
      static_cast<const ActionCommand &>(from));
}


void ActionCommand::MergeFrom(const ActionCommand& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ActionCommand)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  numrobots_.MergeFrom(from.numrobots_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ActionCommand::CopyFrom(const ActionCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ActionCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ActionCommand::IsInitialized() const {
  return true;
}

void ActionCommand::InternalSwap(ActionCommand* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  numrobots_.InternalSwap(&other->numrobots_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ActionCommand::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ActionCommand_2eproto_getter, &descriptor_table_ActionCommand_2eproto_once,
      file_level_metadata_ActionCommand_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ActionCommand*
Arena::CreateMaybeMessage< ::ActionCommand >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ActionCommand >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
