# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RobotParameters.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15RobotParameters.proto\x12\x05proto\"r\n\x0fRobotParameters\x12\x0e\n\x06radius\x18\x01 \x01(\x02\x12\x0e\n\x06height\x18\x02 \x01(\x02\x12\x13\n\x0b\x66ront_width\x18\x03 \x01(\x02\x12\x16\n\x0e\x64ribbler_width\x18\x04 \x01(\x02\x12\x12\n\nyaw_offset\x18\x05 \x01(\x02\"O\n\x0eTeamParameters\x12\x11\n\tdidChange\x18\x01 \x01(\x08\x12*\n\nparameters\x18\x02 \x01(\x0b\x32\x16.proto.RobotParametersb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RobotParameters_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROBOTPARAMETERS._serialized_start=32
  _ROBOTPARAMETERS._serialized_end=146
  _TEAMPARAMETERS._serialized_start=148
  _TEAMPARAMETERS._serialized_end=227
# @@protoc_insertion_point(module_scope)
