# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: State.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import World_pb2 as World__pb2
from . import RobotParameters_pb2 as RobotParameters__pb2
from . import messages_robocup_ssl_wrapper_pb2 as messages__robocup__ssl__wrapper__pb2
from . import messages_robocup_ssl_referee_pb2 as messages__robocup__ssl__referee__pb2
from . import messages_robocup_ssl_geometry_pb2 as messages__robocup__ssl__geometry__pb2
from . import RobotFeedback_pb2 as RobotFeedback__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bState.proto\x12\x05proto\x1a\x0bWorld.proto\x1a\x15RobotParameters.proto\x1a\"messages_robocup_ssl_wrapper.proto\x1a\"messages_robocup_ssl_referee.proto\x1a#messages_robocup_ssl_geometry.proto\x1a\x13RobotFeedback.proto\"\xea\x03\n\x05State\x12%\n\x0flast_seen_world\x18\x01 \x01(\x0b\x32\x0c.proto.World\x12\x30\n\x1a\x63ommand_extrapolated_world\x18\x02 \x01(\x0b\x32\x0c.proto.World\x12\'\n\x11\x62\x61ll_camera_world\x18\x03 \x01(\x0b\x32\x0c.proto.World\x12\x34\n\x15\x62lue_robot_parameters\x18\x04 \x01(\x0b\x32\x15.proto.TeamParameters\x12\x36\n\x17yellow_robot_parameters\x18\x05 \x01(\x0b\x32\x15.proto.TeamParameters\x12&\n\x05\x66ield\x18\x06 \x01(\x0b\x32\x17.proto.SSL_GeometryData\x12\x1f\n\x07referee\x18\x07 \x01(\x0b\x32\x0e.proto.Referee\x12:\n\x18processed_vision_packets\x18\n \x03(\x0b\x32\x18.proto.SSL_WrapperPacket\x12\x31\n\x19processed_referee_packets\x18\x0b \x03(\x0b\x32\x0e.proto.Referee\x12\x39\n\x1aprocessed_feedback_packets\x18\x0c \x03(\x0b\x32\x15.proto.RobotsFeedbackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'State_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATE']._serialized_start=189
  _globals['_STATE']._serialized_end=679
# @@protoc_insertion_point(module_scope)
