# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RobotCommands.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13RobotCommands.proto\x12\x05proto\"\x9d\x03\n\x0cRobotCommand\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nvelocity_x\x18\x02 \x01(\x01\x12\x12\n\nvelocity_y\x18\x03 \x01(\x01\x12\r\n\x05\x61ngle\x18\x04 \x01(\x01\x12\x18\n\x10\x61ngular_velocity\x18\x05 \x01(\x01\x12\x1c\n\x14use_angular_velocity\x18\x06 \x01(\x08\x12\x1d\n\x15\x63\x61mera_angle_of_robot\x18\x07 \x01(\x01\x12$\n\x1c\x63\x61mera_angle_of_robot_is_set\x18\x08 \x01(\x08\x12\x12\n\nkick_speed\x18\t \x01(\x01\x12\x15\n\rwait_for_ball\x18\n \x01(\x08\x12\x15\n\rkick_at_angle\x18\x0b \x01(\x08\x12/\n\tkick_type\x18\x0c \x01(\x0e\x32\x1c.proto.RobotCommand.KickType\x12\x16\n\x0e\x64ribbler_speed\x18\r \x01(\x01\x12\x15\n\rwheels_off\x18\x0e \x01(\x08\"+\n\x08KickType\x12\x0b\n\x07NO_KICK\x10\x00\x12\x08\n\x04KICK\x10\x01\x12\x08\n\x04\x43HIP\x10\x02\"<\n\rRobotCommands\x12+\n\x0erobot_commands\x18\x01 \x03(\x0b\x32\x13.proto.RobotCommandb\x06proto3')



_ROBOTCOMMAND = DESCRIPTOR.message_types_by_name['RobotCommand']
_ROBOTCOMMANDS = DESCRIPTOR.message_types_by_name['RobotCommands']
_ROBOTCOMMAND_KICKTYPE = _ROBOTCOMMAND.enum_types_by_name['KickType']
RobotCommand = _reflection.GeneratedProtocolMessageType('RobotCommand', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTCOMMAND,
  '__module__' : 'RobotCommands_pb2'
  # @@protoc_insertion_point(class_scope:proto.RobotCommand)
  })
_sym_db.RegisterMessage(RobotCommand)

RobotCommands = _reflection.GeneratedProtocolMessageType('RobotCommands', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTCOMMANDS,
  '__module__' : 'RobotCommands_pb2'
  # @@protoc_insertion_point(class_scope:proto.RobotCommands)
  })
_sym_db.RegisterMessage(RobotCommands)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROBOTCOMMAND._serialized_start=31
  _ROBOTCOMMAND._serialized_end=444
  _ROBOTCOMMAND_KICKTYPE._serialized_start=401
  _ROBOTCOMMAND_KICKTYPE._serialized_end=444
  _ROBOTCOMMANDS._serialized_start=446
  _ROBOTCOMMANDS._serialized_end=506
# @@protoc_insertion_point(module_scope)
