from datetime import datetime
import shutil

import generators as g
from packets import packets

for packetName in packets.keys():

	filename = "%s.h" % packetName
	file = open("generated/" + filename, "w")

	timestamp = datetime.now()

	file.write("// AUTOGENERATED. Run generator/main.py to regenerate\n")
	file.write("// Generated on %s\n\n" % timestamp.strftime("%B %d %Y, %H:%M:%S"))
	
	file.write("#ifndef %s\n" % g.toHeaderGuard(packetName))
	file.write("#define %s\n" % g.toHeaderGuard(packetName))
	file.write("\n")
	file.write("#include <stdbool.h>\n")
	file.write("#include <stdint.h>\n")
	file.write("#include \"BaseTypes.h\"\n")
	file.write("\n")
	file.write("%s\n" % g.toStructPayload(packetName))
	
	file.write("\n\n\n/** ================================ PACKET ================================ \n")
	file.write(g.toStructure(packetName, packets[packetName]))
	file.write("\n*/")
	file.write("\n")
	
	file.write("\n\n\n/** ================================ STRUCT ================================ */\n")
	file.write(g.toStruct(packetName, packets[packetName]))
	file.write("\n")

	file.write("\n\n\n/** ================================ GETTERS ================================ */\n")
	file.write("%s\n" % g.toGetters(packetName, packets))

	file.write("\n\n/** ================================ SETTERS ================================ */\n")
	file.write("%s\n" % g.toSetters(packetName, packets))

	file.write("\n\n/** ================================ DECODE ================================ */\n")
	file.write(g.toDecode(packetName, packets[packetName]))
	file.write("\n")

	file.write("\n\n\n/** ================================ ENCODE ================================ */\n")
	file.write(g.toEncode(packetName, packets[packetName]))
	file.write("\n")
	file.write("\n")
	file.write("#endif /*%s*/\n" % g.toHeaderGuard(packetName))

	file.close()

	shutil.copy("generated/%s" % filename, "../include/%s" % filename)
