if (APPLE)
    if (EXISTS /usr/local/opt/qt@5)
        list(APPEND CMAKE_PREFIX_PATH "/usr/local/opt/qt@5")
    elseif(EXISTS /usr/local/opt/qt5)
        list(APPEND CMAKE_PREFIX_PATH "/usr/local/opt/qt5")
    else()
        message(FATAL_ERROR "Could not find Qt5. Please install with `brew install qt@5`.")
    endif()
elseif(UNIX AND NOT APPLE)
    list(APPEND CMAKE_PREFIX_PATH "/usr/lib/x86_64-linux-gnu/cmake/Qt5")
else()
    message(FATAL_ERROR "Can't auto-locate Qt5 for this platform")
endif()