var annotated_dup =
[
    [ "BaseTypeGenerator", "namespaceBaseTypeGenerator.html", [
      [ "BaseTypeGenerator", "classBaseTypeGenerator_1_1BaseTypeGenerator.html", "classBaseTypeGenerator_1_1BaseTypeGenerator" ],
      [ "C_BaseTypeGenerator", "classBaseTypeGenerator_1_1C__BaseTypeGenerator.html", "classBaseTypeGenerator_1_1C__BaseTypeGenerator" ],
      [ "Python_BaseTypeGenerator", "classBaseTypeGenerator_1_1Python__BaseTypeGenerator.html", "classBaseTypeGenerator_1_1Python__BaseTypeGenerator" ]
    ] ],
    [ "Generator", "namespaceGenerator.html", [
      [ "Generator", "classGenerator_1_1Generator.html", "classGenerator_1_1Generator" ],
      [ "C_Generator", "classGenerator_1_1C__Generator.html", "classGenerator_1_1C__Generator" ],
      [ "Python_Generator", "classGenerator_1_1Python__Generator.html", "classGenerator_1_1Python__Generator" ],
      [ "Proto_Generator", "classGenerator_1_1Proto__Generator.html", "classGenerator_1_1Proto__Generator" ]
    ] ],
    [ "nativeformat", "namespacenativeformat.html", [
      [ "param", "namespacenativeformat_1_1param.html", [
        [ "Param", "classnativeformat_1_1param_1_1Param.html", "classnativeformat_1_1param_1_1Param" ],
        [ "ParamEvent", "structnativeformat_1_1param_1_1ParamEvent.html", "structnativeformat_1_1param_1_1ParamEvent" ],
        [ "ParamImplementation", "classnativeformat_1_1param_1_1ParamImplementation.html", "classnativeformat_1_1param_1_1ParamImplementation" ],
        [ "ValueAtTimeEvent", "structnativeformat_1_1param_1_1ValueAtTimeEvent.html", "structnativeformat_1_1param_1_1ValueAtTimeEvent" ],
        [ "LinearRampEvent", "structnativeformat_1_1param_1_1LinearRampEvent.html", "structnativeformat_1_1param_1_1LinearRampEvent" ],
        [ "DummyEvent", "structnativeformat_1_1param_1_1DummyEvent.html", "structnativeformat_1_1param_1_1DummyEvent" ]
      ] ]
    ] ],
    [ "roboteam_utils", "namespaceroboteam__utils.html", [
      [ "Timer", "classroboteam__utils_1_1Timer.html", "classroboteam__utils_1_1Timer" ]
    ] ],
    [ "rtt", "namespacertt.html", [
      [ "ai", "namespacertt_1_1ai.html", [
        [ "control", "namespacertt_1_1ai_1_1control.html", [
          [ "ControlModule", "classrtt_1_1ai_1_1control_1_1ControlModule.html", "classrtt_1_1ai_1_1control_1_1ControlModule" ],
          [ "ControlUtils", "classrtt_1_1ai_1_1control_1_1ControlUtils.html", "classrtt_1_1ai_1_1control_1_1ControlUtils" ],
          [ "CollisionDetector", "classrtt_1_1ai_1_1control_1_1CollisionDetector.html", "classrtt_1_1ai_1_1control_1_1CollisionDetector" ],
          [ "NumTreesPlanning", "classrtt_1_1ai_1_1control_1_1NumTreesPlanning.html", "classrtt_1_1ai_1_1control_1_1NumTreesPlanning" ],
          [ "PathPlanningAlgorithm", "classrtt_1_1ai_1_1control_1_1PathPlanningAlgorithm.html", "classrtt_1_1ai_1_1control_1_1PathPlanningAlgorithm" ],
          [ "PathPointNode", "classrtt_1_1ai_1_1control_1_1PathPointNode.html", "classrtt_1_1ai_1_1control_1_1PathPointNode" ],
          [ "BBTPathTracking", "classrtt_1_1ai_1_1control_1_1BBTPathTracking.html", "classrtt_1_1ai_1_1control_1_1BBTPathTracking" ],
          [ "DensePathTracking", "classrtt_1_1ai_1_1control_1_1DensePathTracking.html", "classrtt_1_1ai_1_1control_1_1DensePathTracking" ],
          [ "PathTrackingAlgorithm", "classrtt_1_1ai_1_1control_1_1PathTrackingAlgorithm.html", "classrtt_1_1ai_1_1control_1_1PathTrackingAlgorithm" ],
          [ "PidTracking", "classrtt_1_1ai_1_1control_1_1PidTracking.html", "classrtt_1_1ai_1_1control_1_1PidTracking" ],
          [ "PositionControl", "classrtt_1_1ai_1_1control_1_1PositionControl.html", "classrtt_1_1ai_1_1control_1_1PositionControl" ],
          [ "PositionControlUtils", "classrtt_1_1ai_1_1control_1_1PositionControlUtils.html", "classrtt_1_1ai_1_1control_1_1PositionControlUtils" ]
        ] ],
        [ "interface", "namespacertt_1_1ai_1_1interface.html", [
          [ "Drawing", "structrtt_1_1ai_1_1interface_1_1Drawing.html", "structrtt_1_1ai_1_1interface_1_1Drawing" ],
          [ "Input", "classrtt_1_1ai_1_1interface_1_1Input.html", "classrtt_1_1ai_1_1interface_1_1Input" ],
          [ "Output", "classrtt_1_1ai_1_1interface_1_1Output.html", "classrtt_1_1ai_1_1interface_1_1Output" ],
          [ "Toggle", "classrtt_1_1ai_1_1interface_1_1Toggle.html", "classrtt_1_1ai_1_1interface_1_1Toggle" ],
          [ "Toggles", "classrtt_1_1ai_1_1interface_1_1Toggles.html", "classrtt_1_1ai_1_1interface_1_1Toggles" ],
          [ "GraphWidget", "classrtt_1_1ai_1_1interface_1_1GraphWidget.html", "classrtt_1_1ai_1_1interface_1_1GraphWidget" ],
          [ "MainControlsWidget", "classrtt_1_1ai_1_1interface_1_1MainControlsWidget.html", "classrtt_1_1ai_1_1interface_1_1MainControlsWidget" ],
          [ "MainWindow", "classrtt_1_1ai_1_1interface_1_1MainWindow.html", "classrtt_1_1ai_1_1interface_1_1MainWindow" ],
          [ "ManualControlWidget", "classrtt_1_1ai_1_1interface_1_1ManualControlWidget.html", "classrtt_1_1ai_1_1interface_1_1ManualControlWidget" ],
          [ "PidBox", "classrtt_1_1ai_1_1interface_1_1PidBox.html", "classrtt_1_1ai_1_1interface_1_1PidBox" ],
          [ "PidsWidget", "classrtt_1_1ai_1_1interface_1_1PidsWidget.html", "classrtt_1_1ai_1_1interface_1_1PidsWidget" ],
          [ "PlaysWidget", "classrtt_1_1ai_1_1interface_1_1PlaysWidget.html", "classrtt_1_1ai_1_1interface_1_1PlaysWidget" ],
          [ "RobotsWidget", "classrtt_1_1ai_1_1interface_1_1RobotsWidget.html", "classrtt_1_1ai_1_1interface_1_1RobotsWidget" ],
          [ "RuleSetWidget", "classrtt_1_1ai_1_1interface_1_1RuleSetWidget.html", "classrtt_1_1ai_1_1interface_1_1RuleSetWidget" ],
          [ "SettingsWidget", "classrtt_1_1ai_1_1interface_1_1SettingsWidget.html", "classrtt_1_1ai_1_1interface_1_1SettingsWidget" ],
          [ "STPVisualizerWidget", "classrtt_1_1ai_1_1interface_1_1STPVisualizerWidget.html", "classrtt_1_1ai_1_1interface_1_1STPVisualizerWidget" ],
          [ "VisualizationSettingsWidget", "classrtt_1_1ai_1_1interface_1_1VisualizationSettingsWidget.html", "classrtt_1_1ai_1_1interface_1_1VisualizationSettingsWidget" ],
          [ "Visualizer", "classrtt_1_1ai_1_1interface_1_1Visualizer.html", "classrtt_1_1ai_1_1interface_1_1Visualizer" ]
        ] ],
        [ "io", "namespacertt_1_1ai_1_1io.html", [
          [ "IOManager", "classrtt_1_1ai_1_1io_1_1IOManager.html", "classrtt_1_1ai_1_1io_1_1IOManager" ]
        ] ],
        [ "stp", "namespacertt_1_1ai_1_1stp.html", [
          [ "computations", "namespacertt_1_1ai_1_1stp_1_1computations.html", [
            [ "GoalComputations", "classrtt_1_1ai_1_1stp_1_1computations_1_1GoalComputations.html", "classrtt_1_1ai_1_1stp_1_1computations_1_1GoalComputations" ],
            [ "PassComputations", "classrtt_1_1ai_1_1stp_1_1computations_1_1PassComputations.html", "classrtt_1_1ai_1_1stp_1_1computations_1_1PassComputations" ]
          ] ],
          [ "evaluation", "namespacertt_1_1ai_1_1stp_1_1evaluation.html", [
            [ "BaseEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BaseEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BaseEvaluation" ],
            [ "BallPlacementThemGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallPlacementThemGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallPlacementThemGameStateEvaluation" ],
            [ "BallPlacementUsGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallPlacementUsGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallPlacementUsGameStateEvaluation" ],
            [ "FreeKickThemGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1FreeKickThemGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1FreeKickThemGameStateEvaluation" ],
            [ "FreeKickUsGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1FreeKickUsGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1FreeKickUsGameStateEvaluation" ],
            [ "HaltGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1HaltGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1HaltGameStateEvaluation" ],
            [ "KickOffThemGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffThemGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffThemGameStateEvaluation" ],
            [ "KickOffThemPrepareGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffThemPrepareGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffThemPrepareGameStateEvaluation" ],
            [ "KickOffUsGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffUsGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffUsGameStateEvaluation" ],
            [ "KickOffUsOrNormalGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffUsOrNormalGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffUsOrNormalGameStateEvaluation" ],
            [ "KickOffUsPrepareGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffUsPrepareGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1KickOffUsPrepareGameStateEvaluation" ],
            [ "NormalOrFreeKickUsGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1NormalOrFreeKickUsGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1NormalOrFreeKickUsGameStateEvaluation" ],
            [ "NormalPlayGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1NormalPlayGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1NormalPlayGameStateEvaluation" ],
            [ "PenaltyThemGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1PenaltyThemGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1PenaltyThemGameStateEvaluation" ],
            [ "PenaltyThemPrepareGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1PenaltyThemPrepareGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1PenaltyThemPrepareGameStateEvaluation" ],
            [ "PenaltyUsGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1PenaltyUsGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1PenaltyUsGameStateEvaluation" ],
            [ "PenaltyUsPrepareGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1PenaltyUsPrepareGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1PenaltyUsPrepareGameStateEvaluation" ],
            [ "StopGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1StopGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1StopGameStateEvaluation" ],
            [ "TimeOutGameStateEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1TimeOutGameStateEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1TimeOutGameStateEvaluation" ],
            [ "BallClosestToUsGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallClosestToUsGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallClosestToUsGlobalEvaluation" ],
            [ "BallCloseToThemGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallCloseToThemGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallCloseToThemGlobalEvaluation" ],
            [ "BallCloseToUsGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallCloseToUsGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallCloseToUsGlobalEvaluation" ],
            [ "BallGotShotGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallGotShotGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallGotShotGlobalEvaluation" ],
            [ "BallInOurDefenseAreaAndStillGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallInOurDefenseAreaAndStillGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallInOurDefenseAreaAndStillGlobalEvaluation" ],
            [ "BallIsFreeGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallIsFreeGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallIsFreeGlobalEvaluation" ],
            [ "BallMovesSlowGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallMovesSlowGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallMovesSlowGlobalEvaluation" ],
            [ "BallNotInOurDefenseAreaAndStillGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallNotInOurDefenseAreaAndStillGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallNotInOurDefenseAreaAndStillGlobalEvaluation" ],
            [ "BallOnOurSideGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallOnOurSideGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallOnOurSideGlobalEvaluation" ],
            [ "BallOnTheirSideGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallOnTheirSideGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BallOnTheirSideGlobalEvaluation" ],
            [ "DistanceFromBallGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1DistanceFromBallGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1DistanceFromBallGlobalEvaluation" ],
            [ "FreedomOfRobotsGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1FreedomOfRobotsGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1FreedomOfRobotsGlobalEvaluation" ],
            [ "GoalVisionFromBallGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1GoalVisionFromBallGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1GoalVisionFromBallGlobalEvaluation" ],
            [ "GoalVisionGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1GoalVisionGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1GoalVisionGlobalEvaluation" ],
            [ "NoGoalVisionFromBallGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1NoGoalVisionFromBallGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1NoGoalVisionFromBallGlobalEvaluation" ],
            [ "TheyDoNotHaveBallGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1TheyDoNotHaveBallGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1TheyDoNotHaveBallGlobalEvaluation" ],
            [ "TheyHaveBallGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1TheyHaveBallGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1TheyHaveBallGlobalEvaluation" ],
            [ "WeHaveBallGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1WeHaveBallGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1WeHaveBallGlobalEvaluation" ],
            [ "WeHaveMajorityGlobalEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1WeHaveMajorityGlobalEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1WeHaveMajorityGlobalEvaluation" ],
            [ "BlockingEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BlockingEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1BlockingEvaluation" ],
            [ "GoalShotEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1GoalShotEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1GoalShotEvaluation" ],
            [ "LineOfSightEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1LineOfSightEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1LineOfSightEvaluation" ],
            [ "OpennessEvaluation", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1OpennessEvaluation.html", "classrtt_1_1ai_1_1stp_1_1evaluation_1_1OpennessEvaluation" ]
          ] ],
          [ "gen", "namespacertt_1_1ai_1_1stp_1_1gen.html", [
            [ "PositionScores", "namespacertt_1_1ai_1_1stp_1_1gen.html#structrtt_1_1ai_1_1stp_1_1gen_1_1PositionScores", "namespacertt_1_1ai_1_1stp_1_1gen_structrtt_1_1ai_1_1stp_1_1gen_1_1PositionScores_dup" ],
            [ "ScoreProfile", "namespacertt_1_1ai_1_1stp_1_1gen.html#structrtt_1_1ai_1_1stp_1_1gen_1_1ScoreProfile", "namespacertt_1_1ai_1_1stp_1_1gen_structrtt_1_1ai_1_1stp_1_1gen_1_1ScoreProfile_dup" ],
            [ "ScoredPosition", "namespacertt_1_1ai_1_1stp_1_1gen.html#structrtt_1_1ai_1_1stp_1_1gen_1_1ScoredPosition", "namespacertt_1_1ai_1_1stp_1_1gen_structrtt_1_1ai_1_1stp_1_1gen_1_1ScoredPosition_dup" ],
            [ "StoreInfo", "namespacertt_1_1ai_1_1stp_1_1gen.html#structrtt_1_1ai_1_1stp_1_1gen_1_1StoreInfo", "namespacertt_1_1ai_1_1stp_1_1gen_structrtt_1_1ai_1_1stp_1_1gen_1_1StoreInfo_dup" ]
          ] ],
          [ "play", "namespacertt_1_1ai_1_1stp_1_1play.html", [
            [ "DefendPass", "classrtt_1_1ai_1_1stp_1_1play_1_1DefendPass.html", "classrtt_1_1ai_1_1stp_1_1play_1_1DefendPass" ],
            [ "DefendShot", "classrtt_1_1ai_1_1stp_1_1play_1_1DefendShot.html", "classrtt_1_1ai_1_1stp_1_1play_1_1DefendShot" ],
            [ "KeeperKickBall", "classrtt_1_1ai_1_1stp_1_1play_1_1KeeperKickBall.html", "classrtt_1_1ai_1_1stp_1_1play_1_1KeeperKickBall" ],
            [ "Attack", "classrtt_1_1ai_1_1stp_1_1play_1_1Attack.html", "classrtt_1_1ai_1_1stp_1_1play_1_1Attack" ],
            [ "AttackingPass", "classrtt_1_1ai_1_1stp_1_1play_1_1AttackingPass.html", "classrtt_1_1ai_1_1stp_1_1play_1_1AttackingPass" ],
            [ "ChippingPass", "classrtt_1_1ai_1_1stp_1_1play_1_1ChippingPass.html", "classrtt_1_1ai_1_1stp_1_1play_1_1ChippingPass" ],
            [ "PlayTemplate", "classrtt_1_1ai_1_1stp_1_1play_1_1PlayTemplate.html", "classrtt_1_1ai_1_1stp_1_1play_1_1PlayTemplate" ],
            [ "AggressiveStopFormation", "classrtt_1_1ai_1_1stp_1_1play_1_1AggressiveStopFormation.html", "classrtt_1_1ai_1_1stp_1_1play_1_1AggressiveStopFormation" ],
            [ "BallPlacementThem", "classrtt_1_1ai_1_1stp_1_1play_1_1BallPlacementThem.html", "classrtt_1_1ai_1_1stp_1_1play_1_1BallPlacementThem" ],
            [ "BallPlacementUs", "classrtt_1_1ai_1_1stp_1_1play_1_1BallPlacementUs.html", "classrtt_1_1ai_1_1stp_1_1play_1_1BallPlacementUs" ],
            [ "DefensiveStopFormation", "classrtt_1_1ai_1_1stp_1_1play_1_1DefensiveStopFormation.html", "classrtt_1_1ai_1_1stp_1_1play_1_1DefensiveStopFormation" ],
            [ "FormationPreHalf", "classrtt_1_1ai_1_1stp_1_1play_1_1FormationPreHalf.html", "classrtt_1_1ai_1_1stp_1_1play_1_1FormationPreHalf" ],
            [ "FreeKickThem", "classrtt_1_1ai_1_1stp_1_1play_1_1FreeKickThem.html", "classrtt_1_1ai_1_1stp_1_1play_1_1FreeKickThem" ],
            [ "FreeKickUsAtGoal", "classrtt_1_1ai_1_1stp_1_1play_1_1FreeKickUsAtGoal.html", "classrtt_1_1ai_1_1stp_1_1play_1_1FreeKickUsAtGoal" ],
            [ "FreeKickUsPass", "classrtt_1_1ai_1_1stp_1_1play_1_1FreeKickUsPass.html", "classrtt_1_1ai_1_1stp_1_1play_1_1FreeKickUsPass" ],
            [ "Halt", "classrtt_1_1ai_1_1stp_1_1play_1_1Halt.html", "classrtt_1_1ai_1_1stp_1_1play_1_1Halt" ],
            [ "KickOffThem", "classrtt_1_1ai_1_1stp_1_1play_1_1KickOffThem.html", "classrtt_1_1ai_1_1stp_1_1play_1_1KickOffThem" ],
            [ "KickOffThemPrepare", "classrtt_1_1ai_1_1stp_1_1play_1_1KickOffThemPrepare.html", "classrtt_1_1ai_1_1stp_1_1play_1_1KickOffThemPrepare" ],
            [ "KickOffUs", "classrtt_1_1ai_1_1stp_1_1play_1_1KickOffUs.html", "classrtt_1_1ai_1_1stp_1_1play_1_1KickOffUs" ],
            [ "KickOffUsPrepare", "classrtt_1_1ai_1_1stp_1_1play_1_1KickOffUsPrepare.html", "classrtt_1_1ai_1_1stp_1_1play_1_1KickOffUsPrepare" ],
            [ "PenaltyThem", "classrtt_1_1ai_1_1stp_1_1play_1_1PenaltyThem.html", "classrtt_1_1ai_1_1stp_1_1play_1_1PenaltyThem" ],
            [ "PenaltyThemPrepare", "classrtt_1_1ai_1_1stp_1_1play_1_1PenaltyThemPrepare.html", "classrtt_1_1ai_1_1stp_1_1play_1_1PenaltyThemPrepare" ],
            [ "PenaltyUs", "classrtt_1_1ai_1_1stp_1_1play_1_1PenaltyUs.html", "classrtt_1_1ai_1_1stp_1_1play_1_1PenaltyUs" ],
            [ "PenaltyUsPrepare", "classrtt_1_1ai_1_1stp_1_1play_1_1PenaltyUsPrepare.html", "classrtt_1_1ai_1_1stp_1_1play_1_1PenaltyUsPrepare" ]
          ] ],
          [ "role", "namespacertt_1_1ai_1_1stp_1_1role.html", [
            [ "Attacker", "classrtt_1_1ai_1_1stp_1_1role_1_1Attacker.html", "classrtt_1_1ai_1_1stp_1_1role_1_1Attacker" ],
            [ "BallPlacer", "classrtt_1_1ai_1_1stp_1_1role_1_1BallPlacer.html", "classrtt_1_1ai_1_1stp_1_1role_1_1BallPlacer" ],
            [ "Chipper", "classrtt_1_1ai_1_1stp_1_1role_1_1Chipper.html", "classrtt_1_1ai_1_1stp_1_1role_1_1Chipper" ],
            [ "FreeKickTaker", "classrtt_1_1ai_1_1stp_1_1role_1_1FreeKickTaker.html", "classrtt_1_1ai_1_1stp_1_1role_1_1FreeKickTaker" ],
            [ "Harasser", "classrtt_1_1ai_1_1stp_1_1role_1_1Harasser.html", "classrtt_1_1ai_1_1stp_1_1role_1_1Harasser" ],
            [ "KeeperPasser", "classrtt_1_1ai_1_1stp_1_1role_1_1KeeperPasser.html", "classrtt_1_1ai_1_1stp_1_1role_1_1KeeperPasser" ],
            [ "Passer", "classrtt_1_1ai_1_1stp_1_1role_1_1Passer.html", "classrtt_1_1ai_1_1stp_1_1role_1_1Passer" ],
            [ "PassReceiver", "classrtt_1_1ai_1_1stp_1_1role_1_1PassReceiver.html", "classrtt_1_1ai_1_1stp_1_1role_1_1PassReceiver" ],
            [ "Keeper", "classrtt_1_1ai_1_1stp_1_1role_1_1Keeper.html", "classrtt_1_1ai_1_1stp_1_1role_1_1Keeper" ],
            [ "BallAvoider", "classrtt_1_1ai_1_1stp_1_1role_1_1BallAvoider.html", "classrtt_1_1ai_1_1stp_1_1role_1_1BallAvoider" ],
            [ "BallDefender", "classrtt_1_1ai_1_1stp_1_1role_1_1BallDefender.html", "classrtt_1_1ai_1_1stp_1_1role_1_1BallDefender" ],
            [ "Formation", "classrtt_1_1ai_1_1stp_1_1role_1_1Formation.html", "classrtt_1_1ai_1_1stp_1_1role_1_1Formation" ],
            [ "Halt", "classrtt_1_1ai_1_1stp_1_1role_1_1Halt.html", "classrtt_1_1ai_1_1stp_1_1role_1_1Halt" ],
            [ "RobotDefender", "classrtt_1_1ai_1_1stp_1_1role_1_1RobotDefender.html", "classrtt_1_1ai_1_1stp_1_1role_1_1RobotDefender" ],
            [ "PenaltyKeeper", "classrtt_1_1ai_1_1stp_1_1role_1_1PenaltyKeeper.html", "classrtt_1_1ai_1_1stp_1_1role_1_1PenaltyKeeper" ]
          ] ],
          [ "skill", "namespacertt_1_1ai_1_1stp_1_1skill.html", [
            [ "Chip", "classrtt_1_1ai_1_1stp_1_1skill_1_1Chip.html", "classrtt_1_1ai_1_1stp_1_1skill_1_1Chip" ],
            [ "GoToPos", "classrtt_1_1ai_1_1stp_1_1skill_1_1GoToPos.html", "classrtt_1_1ai_1_1stp_1_1skill_1_1GoToPos" ],
            [ "Kick", "classrtt_1_1ai_1_1stp_1_1skill_1_1Kick.html", "classrtt_1_1ai_1_1stp_1_1skill_1_1Kick" ],
            [ "Orbit", "classrtt_1_1ai_1_1stp_1_1skill_1_1Orbit.html", "classrtt_1_1ai_1_1stp_1_1skill_1_1Orbit" ],
            [ "OrbitAngular", "classrtt_1_1ai_1_1stp_1_1skill_1_1OrbitAngular.html", "classrtt_1_1ai_1_1stp_1_1skill_1_1OrbitAngular" ],
            [ "Rotate", "classrtt_1_1ai_1_1stp_1_1skill_1_1Rotate.html", "classrtt_1_1ai_1_1stp_1_1skill_1_1Rotate" ],
            [ "TestSkill", "classrtt_1_1ai_1_1stp_1_1skill_1_1TestSkill.html", "classrtt_1_1ai_1_1stp_1_1skill_1_1TestSkill" ]
          ] ],
          [ "tactic", "namespacertt_1_1ai_1_1stp_1_1tactic.html", [
            [ "ChipAtPos", "classrtt_1_1ai_1_1stp_1_1tactic_1_1ChipAtPos.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1ChipAtPos" ],
            [ "DriveWithBall", "classrtt_1_1ai_1_1stp_1_1tactic_1_1DriveWithBall.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1DriveWithBall" ],
            [ "GetBall", "classrtt_1_1ai_1_1stp_1_1tactic_1_1GetBall.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1GetBall" ],
            [ "GetBehindBallInDirection", "classrtt_1_1ai_1_1stp_1_1tactic_1_1GetBehindBallInDirection.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1GetBehindBallInDirection" ],
            [ "KickAtPos", "classrtt_1_1ai_1_1stp_1_1tactic_1_1KickAtPos.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1KickAtPos" ],
            [ "OrbitKick", "classrtt_1_1ai_1_1stp_1_1tactic_1_1OrbitKick.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1OrbitKick" ],
            [ "Receive", "classrtt_1_1ai_1_1stp_1_1tactic_1_1Receive.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1Receive" ],
            [ "KeeperBlockBall", "classrtt_1_1ai_1_1stp_1_1tactic_1_1KeeperBlockBall.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1KeeperBlockBall" ],
            [ "AvoidBall", "classrtt_1_1ai_1_1stp_1_1tactic_1_1AvoidBall.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1AvoidBall" ],
            [ "BallStandBack", "classrtt_1_1ai_1_1stp_1_1tactic_1_1BallStandBack.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1BallStandBack" ],
            [ "BlockBall", "classrtt_1_1ai_1_1stp_1_1tactic_1_1BlockBall.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1BlockBall" ],
            [ "BlockRobot", "classrtt_1_1ai_1_1stp_1_1tactic_1_1BlockRobot.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1BlockRobot" ],
            [ "Formation", "classrtt_1_1ai_1_1stp_1_1tactic_1_1Formation.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1Formation" ],
            [ "Halt", "classrtt_1_1ai_1_1stp_1_1tactic_1_1Halt.html", "classrtt_1_1ai_1_1stp_1_1tactic_1_1Halt" ]
          ] ],
          [ "ComputationManager", "classrtt_1_1ai_1_1stp_1_1ComputationManager.html", "classrtt_1_1ai_1_1stp_1_1ComputationManager" ],
          [ "PassInfo", "namespacertt_1_1ai_1_1stp.html#structrtt_1_1ai_1_1stp_1_1PassInfo", "namespacertt_1_1ai_1_1stp_structrtt_1_1ai_1_1stp_1_1PassInfo_dup" ],
          [ "PositionComputations", "classrtt_1_1ai_1_1stp_1_1PositionComputations.html", "classrtt_1_1ai_1_1stp_1_1PositionComputations" ],
          [ "PositionScoring", "classrtt_1_1ai_1_1stp_1_1PositionScoring.html", "classrtt_1_1ai_1_1stp_1_1PositionScoring" ],
          [ "Play", "classrtt_1_1ai_1_1stp_1_1Play.html", "classrtt_1_1ai_1_1stp_1_1Play" ],
          [ "PlayDecider", "classrtt_1_1ai_1_1stp_1_1PlayDecider.html", "classrtt_1_1ai_1_1stp_1_1PlayDecider" ],
          [ "PlayEvaluator", "classrtt_1_1ai_1_1stp_1_1PlayEvaluator.html", "classrtt_1_1ai_1_1stp_1_1PlayEvaluator" ],
          [ "Role", "classrtt_1_1ai_1_1stp_1_1Role.html", "classrtt_1_1ai_1_1stp_1_1Role" ],
          [ "TestRole", "classrtt_1_1ai_1_1stp_1_1TestRole.html", "classrtt_1_1ai_1_1stp_1_1TestRole" ],
          [ "Skill", "classrtt_1_1ai_1_1stp_1_1Skill.html", "classrtt_1_1ai_1_1stp_1_1Skill" ],
          [ "StpInfo", "structrtt_1_1ai_1_1stp_1_1StpInfo.html", "structrtt_1_1ai_1_1stp_1_1StpInfo" ],
          [ "Tactic", "classrtt_1_1ai_1_1stp_1_1Tactic.html", "classrtt_1_1ai_1_1stp_1_1Tactic" ],
          [ "TestTactic", "classrtt_1_1ai_1_1stp_1_1TestTactic.html", "classrtt_1_1ai_1_1stp_1_1TestTactic" ],
          [ "AvoidObjects", "namespacertt_1_1ai_1_1stp.html#structrtt_1_1ai_1_1stp_1_1AvoidObjects", "namespacertt_1_1ai_1_1stp_structrtt_1_1ai_1_1stp_1_1AvoidObjects_dup" ]
        ] ],
        [ "Constants", "classrtt_1_1ai_1_1Constants.html", "classrtt_1_1ai_1_1Constants" ],
        [ "Dealer", "classrtt_1_1ai_1_1Dealer.html", "classrtt_1_1ai_1_1Dealer" ],
        [ "GameState", "structrtt_1_1ai_1_1GameState.html", "structrtt_1_1ai_1_1GameState" ],
        [ "GameStateManager", "classrtt_1_1ai_1_1GameStateManager.html", "classrtt_1_1ai_1_1GameStateManager" ],
        [ "Pause", "classrtt_1_1ai_1_1Pause.html", "classrtt_1_1ai_1_1Pause" ],
        [ "RefGameState", "structrtt_1_1ai_1_1RefGameState.html", "structrtt_1_1ai_1_1RefGameState" ],
        [ "RuleSet", "structrtt_1_1ai_1_1RuleSet.html", "structrtt_1_1ai_1_1RuleSet" ],
        [ "StrategyManager", "classrtt_1_1ai_1_1StrategyManager.html", "classrtt_1_1ai_1_1StrategyManager" ],
        [ "BallPossession", "classrtt_1_1ai_1_1BallPossession.html", "classrtt_1_1ai_1_1BallPossession" ],
        [ "FieldComputations", "classrtt_1_1ai_1_1FieldComputations.html", "classrtt_1_1ai_1_1FieldComputations" ]
      ] ],
      [ "BB", "namespacertt_1_1BB.html", [
        [ "BBTrajectoryPart", "namespacertt_1_1BB.html#structrtt_1_1BB_1_1BBTrajectoryPart", "namespacertt_1_1BB_structrtt_1_1BB_1_1BBTrajectoryPart_dup" ],
        [ "BBPosVelAcc", "structrtt_1_1BB_1_1BBPosVelAcc.html", "structrtt_1_1BB_1_1BBPosVelAcc" ],
        [ "BBTrajectory1D", "classrtt_1_1BB_1_1BBTrajectory1D.html", "classrtt_1_1BB_1_1BBTrajectory1D" ],
        [ "BBTrajectory2D", "classrtt_1_1BB_1_1BBTrajectory2D.html", "classrtt_1_1BB_1_1BBTrajectory2D" ],
        [ "CollisionData", "namespacertt_1_1BB.html#structrtt_1_1BB_1_1CollisionData", "namespacertt_1_1BB_structrtt_1_1BB_1_1CollisionData_dup" ],
        [ "CommandCollision", "namespacertt_1_1BB.html#structrtt_1_1BB_1_1CommandCollision", "namespacertt_1_1BB_structrtt_1_1BB_1_1CommandCollision_dup" ],
        [ "WorldObjects", "classrtt_1_1BB_1_1WorldObjects.html", "classrtt_1_1BB_1_1WorldObjects" ]
      ] ],
      [ "collections", "namespacertt_1_1collections.html", [
        [ "circular_buffer", "classrtt_1_1collections_1_1circular__buffer.html", "classrtt_1_1collections_1_1circular__buffer" ],
        [ "state_machine", "classrtt_1_1collections_1_1state__machine.html", "classrtt_1_1collections_1_1state__machine" ],
        [ "static_vector", "classrtt_1_1collections_1_1static__vector.html", "classrtt_1_1collections_1_1static__vector" ]
      ] ],
      [ "input", "namespacertt_1_1input.html", [
        [ "JoystickHandler", "classrtt_1_1input_1_1JoystickHandler.html", "classrtt_1_1input_1_1JoystickHandler" ],
        [ "JoystickManager", "classrtt_1_1input_1_1JoystickManager.html", "classrtt_1_1input_1_1JoystickManager" ],
        [ "JoystickState", "namespacertt_1_1input.html#classrtt_1_1input_1_1JoystickState", "namespacertt_1_1input_classrtt_1_1input_1_1JoystickState_dup" ]
      ] ],
      [ "Interface", "namespacertt_1_1Interface.html", [
        [ "InterfaceControllerServer", "classrtt_1_1Interface_1_1InterfaceControllerServer.html", "classrtt_1_1Interface_1_1InterfaceControllerServer" ],
        [ "InterfaceBallItem", "classrtt_1_1Interface_1_1InterfaceBallItem.html", "classrtt_1_1Interface_1_1InterfaceBallItem" ],
        [ "InterfaceControllerClient", "classrtt_1_1Interface_1_1InterfaceControllerClient.html", "classrtt_1_1Interface_1_1InterfaceControllerClient" ],
        [ "InterfaceFieldRenderer", "classrtt_1_1Interface_1_1InterfaceFieldRenderer.html", "classrtt_1_1Interface_1_1InterfaceFieldRenderer" ],
        [ "InterfaceFieldScene", "classrtt_1_1Interface_1_1InterfaceFieldScene.html", "classrtt_1_1Interface_1_1InterfaceFieldScene" ],
        [ "InterfaceFieldStateStore", "classrtt_1_1Interface_1_1InterfaceFieldStateStore.html", "classrtt_1_1Interface_1_1InterfaceFieldStateStore" ],
        [ "InterfaceFieldView", "classrtt_1_1Interface_1_1InterfaceFieldView.html", "classrtt_1_1Interface_1_1InterfaceFieldView" ],
        [ "InterfaceFieldWidget", "classrtt_1_1Interface_1_1InterfaceFieldWidget.html", "classrtt_1_1Interface_1_1InterfaceFieldWidget" ],
        [ "InterfaceRobotItem", "classrtt_1_1Interface_1_1InterfaceRobotItem.html", "classrtt_1_1Interface_1_1InterfaceRobotItem" ],
        [ "InterfaceRobotPathItem", "classrtt_1_1Interface_1_1InterfaceRobotPathItem.html", "classrtt_1_1Interface_1_1InterfaceRobotPathItem" ],
        [ "InterfaceSyncedCheckableButton", "classrtt_1_1Interface_1_1InterfaceSyncedCheckableButton.html", "classrtt_1_1Interface_1_1InterfaceSyncedCheckableButton" ],
        [ "InterfaceSyncedCheckbox", "classrtt_1_1Interface_1_1InterfaceSyncedCheckbox.html", "classrtt_1_1Interface_1_1InterfaceSyncedCheckbox" ],
        [ "InterfaceSyncedDropdown", "classrtt_1_1Interface_1_1InterfaceSyncedDropdown.html", "classrtt_1_1Interface_1_1InterfaceSyncedDropdown" ],
        [ "InterfaceSyncedSlider", "classrtt_1_1Interface_1_1InterfaceSyncedSlider.html", "classrtt_1_1Interface_1_1InterfaceSyncedSlider" ],
        [ "InterfaceSyncedText", "classrtt_1_1Interface_1_1InterfaceSyncedText.html", "classrtt_1_1Interface_1_1InterfaceSyncedText" ],
        [ "InterfaceWidgetDebugDisplay", "classrtt_1_1Interface_1_1InterfaceWidgetDebugDisplay.html", "classrtt_1_1Interface_1_1InterfaceWidgetDebugDisplay" ],
        [ "InterfaceWidgetRobotDisplay", "classrtt_1_1Interface_1_1InterfaceWidgetRobotDisplay.html", "classrtt_1_1Interface_1_1InterfaceWidgetRobotDisplay" ],
        [ "InterfaceWidgetRobotOverview", "classrtt_1_1Interface_1_1InterfaceWidgetRobotOverview.html", "classrtt_1_1Interface_1_1InterfaceWidgetRobotOverview" ],
        [ "InterfaceWidgetStopButton", "classrtt_1_1Interface_1_1InterfaceWidgetStopButton.html", "classrtt_1_1Interface_1_1InterfaceWidgetStopButton" ],
        [ "MainWindow", "classrtt_1_1Interface_1_1MainWindow.html", "classrtt_1_1Interface_1_1MainWindow" ],
        [ "InterfaceController", "classrtt_1_1Interface_1_1InterfaceController.html", "classrtt_1_1Interface_1_1InterfaceController" ],
        [ "InterfaceSlider", "structrtt_1_1Interface_1_1InterfaceSlider.html", "structrtt_1_1Interface_1_1InterfaceSlider" ],
        [ "InterfaceCheckbox", "structrtt_1_1Interface_1_1InterfaceCheckbox.html", "structrtt_1_1Interface_1_1InterfaceCheckbox" ],
        [ "InterfaceDropdown", "structrtt_1_1Interface_1_1InterfaceDropdown.html", "structrtt_1_1Interface_1_1InterfaceDropdown" ],
        [ "InterfaceRadio", "structrtt_1_1Interface_1_1InterfaceRadio.html", "structrtt_1_1Interface_1_1InterfaceRadio" ],
        [ "InterfaceText", "structrtt_1_1Interface_1_1InterfaceText.html", "structrtt_1_1Interface_1_1InterfaceText" ],
        [ "InterfaceDeclaration", "structrtt_1_1Interface_1_1InterfaceDeclaration.html", "structrtt_1_1Interface_1_1InterfaceDeclaration" ],
        [ "InterfaceDeclarations", "classrtt_1_1Interface_1_1InterfaceDeclarations.html", "classrtt_1_1Interface_1_1InterfaceDeclarations" ],
        [ "InterfaceSettings", "classrtt_1_1Interface_1_1InterfaceSettings.html", "classrtt_1_1Interface_1_1InterfaceSettings" ],
        [ "InterfaceValue", "structrtt_1_1Interface_1_1InterfaceValue.html", "structrtt_1_1Interface_1_1InterfaceValue" ],
        [ "MessageCache", "classrtt_1_1Interface_1_1MessageCache.html", "classrtt_1_1Interface_1_1MessageCache" ]
      ] ],
      [ "net", "namespacertt_1_1net.html", [
        [ "utils", "namespacertt_1_1net_1_1utils.html", [
          [ "Channel", "structrtt_1_1net_1_1utils_1_1Channel.html", "structrtt_1_1net_1_1utils_1_1Channel" ],
          [ "Publisher", "classrtt_1_1net_1_1utils_1_1Publisher.html", "classrtt_1_1net_1_1utils_1_1Publisher" ],
          [ "Subscriber", "classrtt_1_1net_1_1utils_1_1Subscriber.html", "classrtt_1_1net_1_1utils_1_1Subscriber" ],
          [ "InvalidCallbackException", "classrtt_1_1net_1_1utils_1_1InvalidCallbackException.html", "classrtt_1_1net_1_1utils_1_1InvalidCallbackException" ]
        ] ],
        [ "AIYellowDataPublisher", "classrtt_1_1net_1_1AIYellowDataPublisher.html", "classrtt_1_1net_1_1AIYellowDataPublisher" ],
        [ "AIYellowDataSubscriber", "classrtt_1_1net_1_1AIYellowDataSubscriber.html", "classrtt_1_1net_1_1AIYellowDataSubscriber" ],
        [ "AIBlueDataPublisher", "classrtt_1_1net_1_1AIBlueDataPublisher.html", "classrtt_1_1net_1_1AIBlueDataPublisher" ],
        [ "AIBlueDataSubscriber", "classrtt_1_1net_1_1AIBlueDataSubscriber.html", "classrtt_1_1net_1_1AIBlueDataSubscriber" ],
        [ "RobotCommandsBluePublisher", "classrtt_1_1net_1_1RobotCommandsBluePublisher.html", "classrtt_1_1net_1_1RobotCommandsBluePublisher" ],
        [ "RobotCommandsBlueSubscriber", "classrtt_1_1net_1_1RobotCommandsBlueSubscriber.html", "classrtt_1_1net_1_1RobotCommandsBlueSubscriber" ],
        [ "RobotCommandsYellowPublisher", "classrtt_1_1net_1_1RobotCommandsYellowPublisher.html", "classrtt_1_1net_1_1RobotCommandsYellowPublisher" ],
        [ "RobotCommandsYellowSubscriber", "classrtt_1_1net_1_1RobotCommandsYellowSubscriber.html", "classrtt_1_1net_1_1RobotCommandsYellowSubscriber" ],
        [ "RobotFeedbackPublisher", "classrtt_1_1net_1_1RobotFeedbackPublisher.html", "classrtt_1_1net_1_1RobotFeedbackPublisher" ],
        [ "RobotFeedbackSubscriber", "classrtt_1_1net_1_1RobotFeedbackSubscriber.html", "classrtt_1_1net_1_1RobotFeedbackSubscriber" ],
        [ "SettingsPublisher", "classrtt_1_1net_1_1SettingsPublisher.html", "classrtt_1_1net_1_1SettingsPublisher" ],
        [ "SettingsSubscriber", "classrtt_1_1net_1_1SettingsSubscriber.html", "classrtt_1_1net_1_1SettingsSubscriber" ],
        [ "SimulationConfigurationPublisher", "classrtt_1_1net_1_1SimulationConfigurationPublisher.html", "classrtt_1_1net_1_1SimulationConfigurationPublisher" ],
        [ "SimulationConfigurationSubscriber", "classrtt_1_1net_1_1SimulationConfigurationSubscriber.html", "classrtt_1_1net_1_1SimulationConfigurationSubscriber" ],
        [ "WorldPublisher", "classrtt_1_1net_1_1WorldPublisher.html", "classrtt_1_1net_1_1WorldPublisher" ],
        [ "WorldSubscriber", "classrtt_1_1net_1_1WorldSubscriber.html", "classrtt_1_1net_1_1WorldSubscriber" ]
      ] ],
      [ "robothub", "namespacertt_1_1robothub.html", [
        [ "basestation", "namespacertt_1_1robothub_1_1basestation.html", [
          [ "Basestation", "classrtt_1_1robothub_1_1basestation_1_1Basestation.html", "classrtt_1_1robothub_1_1basestation_1_1Basestation" ],
          [ "FailedToOpenDeviceException", "classrtt_1_1robothub_1_1basestation_1_1FailedToOpenDeviceException.html", "classrtt_1_1robothub_1_1basestation_1_1FailedToOpenDeviceException" ],
          [ "BasestationCollection", "classrtt_1_1robothub_1_1basestation_1_1BasestationCollection.html", "classrtt_1_1robothub_1_1basestation_1_1BasestationCollection" ],
          [ "BasestationManager", "classrtt_1_1robothub_1_1basestation_1_1BasestationManager.html", "classrtt_1_1robothub_1_1basestation_1_1BasestationManager" ],
          [ "FailedToInitializeLibUsb", "classrtt_1_1robothub_1_1basestation_1_1FailedToInitializeLibUsb.html", "classrtt_1_1robothub_1_1basestation_1_1FailedToInitializeLibUsb" ]
        ] ],
        [ "simulation", "namespacertt_1_1robothub_1_1simulation.html", [
          [ "ConfigurationCommand", "classrtt_1_1robothub_1_1simulation_1_1ConfigurationCommand.html", "classrtt_1_1robothub_1_1simulation_1_1ConfigurationCommand" ],
          [ "RobotControlCommand", "classrtt_1_1robothub_1_1simulation_1_1RobotControlCommand.html", "classrtt_1_1robothub_1_1simulation_1_1RobotControlCommand" ],
          [ "SimulatorManager", "classrtt_1_1robothub_1_1simulation_1_1SimulatorManager.html", "classrtt_1_1robothub_1_1simulation_1_1SimulatorManager" ],
          [ "FailedToBindPortException", "classrtt_1_1robothub_1_1simulation_1_1FailedToBindPortException.html", "classrtt_1_1robothub_1_1simulation_1_1FailedToBindPortException" ]
        ] ],
        [ "RobotHub", "classrtt_1_1robothub_1_1RobotHub.html", "classrtt_1_1robothub_1_1RobotHub" ],
        [ "FailedToInitializeNetworkersException", "classrtt_1_1robothub_1_1FailedToInitializeNetworkersException.html", "classrtt_1_1robothub_1_1FailedToInitializeNetworkersException" ],
        [ "RobotHubStatistics", "classrtt_1_1robothub_1_1RobotHubStatistics.html", "classrtt_1_1robothub_1_1RobotHubStatistics" ]
      ] ],
      [ "type_traits", "namespacertt_1_1type__traits.html", [
        [ "is_valid_type", "structrtt_1_1type__traits_1_1is__valid__type.html", null ],
        [ "is_valid_type< T, Enum, SI, void, void, void >", "structrtt_1_1type__traits_1_1is__valid__type_3_01T_00_01Enum_00_01SI_00_01void_00_01void_00_01void_01_4.html", null ],
        [ "is_zero_initializable", "structrtt_1_1type__traits_1_1is__zero__initializable.html", null ],
        [ "is_zero_initializable< T, decltype(T(0))>", "structrtt_1_1type__traits_1_1is__zero__initializable_3_01T_00_01decltype_07T_070_08_08_4.html", null ]
      ] ],
      [ "world", "namespacertt_1_1world.html", [
        [ "ball", "namespacertt_1_1world_1_1ball.html", [
          [ "Ball", "classrtt_1_1world_1_1ball_1_1Ball.html", "classrtt_1_1world_1_1ball_1_1Ball" ]
        ] ],
        [ "robot", "namespacertt_1_1world_1_1robot.html", [
          [ "hasBallInfo", "namespacertt_1_1world_1_1robot.html#structrtt_1_1world_1_1robot_1_1hasBallInfo", "namespacertt_1_1world_1_1robot_structrtt_1_1world_1_1robot_1_1hasBallInfo_dup" ],
          [ "Robot", "classrtt_1_1world_1_1robot_1_1Robot.html", "classrtt_1_1world_1_1robot_1_1Robot" ]
        ] ],
        [ "view", "namespacertt_1_1world_1_1view.html", [
          [ "BallView", "classrtt_1_1world_1_1view_1_1BallView.html", "classrtt_1_1world_1_1view_1_1BallView" ],
          [ "RobotView", "classrtt_1_1world_1_1view_1_1RobotView.html", "classrtt_1_1world_1_1view_1_1RobotView" ],
          [ "WorldDataView", "classrtt_1_1world_1_1view_1_1WorldDataView.html", "classrtt_1_1world_1_1view_1_1WorldDataView" ]
        ] ],
        [ "World", "classrtt_1_1world_1_1World.html", "classrtt_1_1world_1_1World" ],
        [ "WorldData", "classrtt_1_1world_1_1WorldData.html", "classrtt_1_1world_1_1WorldData" ]
      ] ],
      [ "AnglePID", "classrtt_1_1AnglePID.html", "classrtt_1_1AnglePID" ],
      [ "Trajectory1D", "classrtt_1_1Trajectory1D.html", "classrtt_1_1Trajectory1D" ],
      [ "Trajectory2D", "classrtt_1_1Trajectory2D.html", "classrtt_1_1Trajectory2D" ],
      [ "STPManager", "classrtt_1_1STPManager.html", "classrtt_1_1STPManager" ],
      [ "Settings", "classrtt_1_1Settings.html", "classrtt_1_1Settings" ],
      [ "BackLogger", "classrtt_1_1BackLogger.html", "classrtt_1_1BackLogger" ],
      [ "LogFileHeader", "structrtt_1_1LogFileHeader.html", "structrtt_1_1LogFileHeader" ],
      [ "LogDataHeader", "namespacertt.html#structrtt_1_1LogDataHeader", "namespacertt_structrtt_1_1LogDataHeader_dup" ],
      [ "LogFileReader", "classrtt_1_1LogFileReader.html", "classrtt_1_1LogFileReader" ],
      [ "LogFileWriter", "classrtt_1_1LogFileWriter.html", "classrtt_1_1LogFileWriter" ],
      [ "RobotHubLogger", "classrtt_1_1RobotHubLogger.html", "classrtt_1_1RobotHubLogger" ],
      [ "Angle", "classrtt_1_1Angle.html", "classrtt_1_1Angle" ],
      [ "Arc", "classrtt_1_1Arc.html", "classrtt_1_1Arc" ],
      [ "Circle", "classrtt_1_1Circle.html", "classrtt_1_1Circle" ],
      [ "Cone", "classrtt_1_1Cone.html", "classrtt_1_1Cone" ],
      [ "BiMap", "classrtt_1_1BiMap.html", "classrtt_1_1BiMap" ],
      [ "FastRectangle", "classrtt_1_1FastRectangle.html", "classrtt_1_1FastRectangle" ],
      [ "FileLogger", "classrtt_1_1FileLogger.html", "classrtt_1_1FileLogger" ],
      [ "FailedToOpenFileException", "classrtt_1_1FailedToOpenFileException.html", "classrtt_1_1FailedToOpenFileException" ],
      [ "Grid", "classrtt_1_1Grid.html", "classrtt_1_1Grid" ],
      [ "HalfLine", "classrtt_1_1HalfLine.html", "classrtt_1_1HalfLine" ],
      [ "Hungarian", "classrtt_1_1Hungarian.html", "classrtt_1_1Hungarian" ],
      [ "LazyRectangle", "classrtt_1_1LazyRectangle.html", "classrtt_1_1LazyRectangle" ],
      [ "Line", "classrtt_1_1Line.html", "classrtt_1_1Line" ],
      [ "LineSegment", "classrtt_1_1LineSegment.html", "classrtt_1_1LineSegment" ],
      [ "PID", "classrtt_1_1PID.html", "classrtt_1_1PID" ],
      [ "Polygon", "classrtt_1_1Polygon.html", "classrtt_1_1Polygon" ],
      [ "Position", "classrtt_1_1Position.html", "classrtt_1_1Position" ],
      [ "Rectangle", "classrtt_1_1Rectangle.html", "classrtt_1_1Rectangle" ],
      [ "RobotShape", "classrtt_1_1RobotShape.html", "classrtt_1_1RobotShape" ],
      [ "Shadow", "classrtt_1_1Shadow.html", "classrtt_1_1Shadow" ],
      [ "Shape", "classrtt_1_1Shape.html", "classrtt_1_1Shape" ],
      [ "Triangle", "classrtt_1_1Triangle.html", "classrtt_1_1Triangle" ],
      [ "Tube", "classrtt_1_1Tube.html", "classrtt_1_1Tube" ],
      [ "Vector2", "classrtt_1_1Vector2.html", "classrtt_1_1Vector2" ]
    ] ],
    [ "std", null, [
      [ "hash< rtt::Vector2 >", "structstd_1_1hash_3_01rtt_1_1Vector2_01_4.html", "structstd_1_1hash_3_01rtt_1_1Vector2_01_4" ]
    ] ],
    [ "testhelpers", "namespacetesthelpers.html", [
      [ "FieldHelper", "classtesthelpers_1_1FieldHelper.html", "classtesthelpers_1_1FieldHelper" ],
      [ "WorldHelper", "classtesthelpers_1_1WorldHelper.html", "classtesthelpers_1_1WorldHelper" ]
    ] ],
    [ "AIData", "structAIData.html", "structAIData" ],
    [ "Ball", "structBall.html", "structBall" ],
    [ "BallAssignmentResult", "structBallAssignmentResult.html", "structBallAssignmentResult" ],
    [ "BallFilter", "classBallFilter.html", "classBallFilter" ],
    [ "BallObservation", "structBallObservation.html", "structBallObservation" ],
    [ "Base", "classBase.html", "classBase" ],
    [ "BasestationCollectionStatus", "BasestationCollection_8hpp.html#structBasestationCollectionStatus", "BasestationCollection_8hpp_structBasestationCollectionStatus" ],
    [ "BasestationIdentifier", "structBasestationIdentifier.html", "structBasestationIdentifier" ],
    [ "BasestationManagerStatus", "BasestationManager_8hpp.html#structBasestationManagerStatus", "BasestationManager_8hpp_structBasestationManagerStatus" ],
    [ "BasestationMessage", "Basestation_8hpp.html#structBasestationMessage", "Basestation_8hpp_structBasestationMessage" ],
    [ "Camera", "classCamera.html", "classCamera" ],
    [ "CameraGroundBallFilter", "classCameraGroundBallFilter.html", "classCameraGroundBallFilter" ],
    [ "CameraGroundBallPrediction", "structCameraGroundBallPrediction.html", "structCameraGroundBallPrediction" ],
    [ "CameraGroundBallPredictionObservationPair", "CameraGroundBallFilter_8h.html#structCameraGroundBallPredictionObservationPair", "CameraGroundBallFilter_8h_structCameraGroundBallPredictionObservationPair" ],
    [ "CameraMap", "classCameraMap.html", "classCameraMap" ],
    [ "CameraObjectFilter", "classCameraObjectFilter.html", "classCameraObjectFilter" ],
    [ "CameraRobotFilter", "classCameraRobotFilter.html", "classCameraRobotFilter" ],
    [ "ConfigurationFeedback", "Feedback_8hpp.html#structConfigurationFeedback", "Feedback_8hpp_structConfigurationFeedback" ],
    [ "Derived", "classDerived.html", "classDerived" ],
    [ "DetectionFrame", "structDetectionFrame.html", "structDetectionFrame" ],
    [ "FailedToInitializeNetworkersException", "classFailedToInitializeNetworkersException.html", "classFailedToInitializeNetworkersException" ],
    [ "FailedToSetupSSLClients", "classFailedToSetupSSLClients.html", "classFailedToSetupSSLClients" ],
    [ "Field", "structField.html", "structField" ],
    [ "FilteredBall", "structFilteredBall.html", "structFilteredBall" ],
    [ "FilteredRobot", "structFilteredRobot.html", "structFilteredRobot" ],
    [ "GeometryFilter", "classGeometryFilter.html", "classGeometryFilter" ],
    [ "GroundBallExtendedKalmanFilter", "classGroundBallExtendedKalmanFilter.html", "classGroundBallExtendedKalmanFilter" ],
    [ "GroundBallPrediction", "structGroundBallPrediction.html", "structGroundBallPrediction" ],
    [ "Handler", "classHandler.html", "classHandler" ],
    [ "KalmanFilter", "classKalmanFilter.html", "classKalmanFilter" ],
    [ "LeftComp", "structLeftComp.html", "structLeftComp" ],
    [ "MockClass", "structMockClass.html", "structMockClass" ],
    [ "MockTactic", "classMockTactic.html", "classMockTactic" ],
    [ "Observer", "classObserver.html", "classObserver" ],
    [ "PosVelFilter1D", "classPosVelFilter1D.html", "classPosVelFilter1D" ],
    [ "PosVelFilter2D", "classPosVelFilter2D.html", "classPosVelFilter2D" ],
    [ "Printer", "classPrinter.html", "classPrinter" ],
    [ "Random", "classRandom.html", "classRandom" ],
    [ "RefereeFilter", "classRefereeFilter.html", "classRefereeFilter" ],
    [ "REM_BasestationConfiguration", "REM__BasestationConfiguration_8h.html#structREM__BasestationConfiguration", "REM__BasestationConfiguration_8h_structREM__BasestationConfiguration" ],
    [ "REM_BasestationConfigurationPayload", "REM__BasestationConfiguration_8h.html#structREM__BasestationConfigurationPayload", "REM__BasestationConfiguration_8h_structREM__BasestationConfigurationPayload" ],
    [ "REM_BasestationGetConfiguration", "REM__BasestationGetConfiguration_8h.html#structREM__BasestationGetConfiguration", "REM__BasestationGetConfiguration_8h_structREM__BasestationGetConfiguration" ],
    [ "REM_BasestationGetConfigurationPayload", "REM__BasestationGetConfiguration_8h.html#structREM__BasestationGetConfigurationPayload", "REM__BasestationGetConfiguration_8h_structREM__BasestationGetConfigurationPayload" ],
    [ "REM_Log", "REM__Log_8h.html#structREM__Log", "REM__Log_8h_structREM__Log" ],
    [ "REM_LogPayload", "REM__Log_8h.html#structREM__LogPayload", "REM__Log_8h_structREM__LogPayload" ],
    [ "REM_Packet", "REM__Packet_8h.html#structREM__Packet", "REM__Packet_8h_structREM__Packet" ],
    [ "REM_PacketPayload", "REM__Packet_8h.html#structREM__PacketPayload", "REM__Packet_8h_structREM__PacketPayload" ],
    [ "REM_RobotAssuredAck", "REM__RobotAssuredAck_8h.html#structREM__RobotAssuredAck", "REM__RobotAssuredAck_8h_structREM__RobotAssuredAck" ],
    [ "REM_RobotAssuredAckPayload", "REM__RobotAssuredAck_8h.html#structREM__RobotAssuredAckPayload", "REM__RobotAssuredAck_8h_structREM__RobotAssuredAckPayload" ],
    [ "REM_RobotAssuredPacket", "REM__RobotAssuredPacket_8h.html#structREM__RobotAssuredPacket", "REM__RobotAssuredPacket_8h_structREM__RobotAssuredPacket" ],
    [ "REM_RobotAssuredPacketPayload", "REM__RobotAssuredPacket_8h.html#structREM__RobotAssuredPacketPayload", "REM__RobotAssuredPacket_8h_structREM__RobotAssuredPacketPayload" ],
    [ "REM_RobotBuzzer", "REM__RobotBuzzer_8h.html#structREM__RobotBuzzer", "REM__RobotBuzzer_8h_structREM__RobotBuzzer" ],
    [ "REM_RobotBuzzerPayload", "REM__RobotBuzzer_8h.html#structREM__RobotBuzzerPayload", "REM__RobotBuzzer_8h_structREM__RobotBuzzerPayload" ],
    [ "REM_RobotCommand", "REM__RobotCommand_8h.html#structREM__RobotCommand", "REM__RobotCommand_8h_structREM__RobotCommand" ],
    [ "REM_RobotCommandPayload", "REM__RobotCommand_8h.html#structREM__RobotCommandPayload", "REM__RobotCommand_8h_structREM__RobotCommandPayload" ],
    [ "REM_RobotFeedback", "REM__RobotFeedback_8h.html#structREM__RobotFeedback", "REM__RobotFeedback_8h_structREM__RobotFeedback" ],
    [ "REM_RobotFeedbackPayload", "REM__RobotFeedback_8h.html#structREM__RobotFeedbackPayload", "REM__RobotFeedback_8h_structREM__RobotFeedbackPayload" ],
    [ "REM_RobotGetPIDGains", "REM__RobotGetPIDGains_8h.html#structREM__RobotGetPIDGains", "REM__RobotGetPIDGains_8h_structREM__RobotGetPIDGains" ],
    [ "REM_RobotGetPIDGainsPayload", "REM__RobotGetPIDGains_8h.html#structREM__RobotGetPIDGainsPayload", "REM__RobotGetPIDGains_8h_structREM__RobotGetPIDGainsPayload" ],
    [ "REM_RobotMusicCommand", "REM__RobotMusicCommand_8h.html#structREM__RobotMusicCommand", "REM__RobotMusicCommand_8h_structREM__RobotMusicCommand" ],
    [ "REM_RobotMusicCommandPayload", "REM__RobotMusicCommand_8h.html#structREM__RobotMusicCommandPayload", "REM__RobotMusicCommand_8h_structREM__RobotMusicCommandPayload" ],
    [ "REM_RobotPIDGains", "REM__RobotPIDGains_8h.html#structREM__RobotPIDGains", "REM__RobotPIDGains_8h_structREM__RobotPIDGains" ],
    [ "REM_RobotPIDGainsPayload", "REM__RobotPIDGains_8h.html#structREM__RobotPIDGainsPayload", "REM__RobotPIDGains_8h_structREM__RobotPIDGainsPayload" ],
    [ "REM_RobotSetPIDGains", "REM__RobotSetPIDGains_8h.html#structREM__RobotSetPIDGains", "REM__RobotSetPIDGains_8h_structREM__RobotSetPIDGains" ],
    [ "REM_RobotSetPIDGainsPayload", "REM__RobotSetPIDGains_8h.html#structREM__RobotSetPIDGainsPayload", "REM__RobotSetPIDGains_8h_structREM__RobotSetPIDGainsPayload" ],
    [ "REM_RobotStateInfo", "REM__RobotStateInfo_8h.html#structREM__RobotStateInfo", "REM__RobotStateInfo_8h_structREM__RobotStateInfo" ],
    [ "REM_RobotStateInfoPayload", "REM__RobotStateInfo_8h.html#structREM__RobotStateInfoPayload", "REM__RobotStateInfo_8h_structREM__RobotStateInfoPayload" ],
    [ "REM_SX1280Filler", "REM__SX1280Filler_8h.html#structREM__SX1280Filler", "REM__SX1280Filler_8h_structREM__SX1280Filler" ],
    [ "REM_SX1280FillerPayload", "REM__SX1280Filler_8h.html#structREM__SX1280FillerPayload", "REM__SX1280Filler_8h_structREM__SX1280FillerPayload" ],
    [ "RightComp", "structRightComp.html", "structRightComp" ],
    [ "RobocupReceiver", "classRobocupReceiver.html", "classRobocupReceiver" ],
    [ "Robot", "structRobot.html", "structRobot" ],
    [ "RobotCommand", "structRobotCommand.html", "structRobotCommand" ],
    [ "RobotControlFeedback", "Feedback_8hpp.html#structRobotControlFeedback", "Feedback_8hpp_structRobotControlFeedback" ],
    [ "RobotFeedback", "structRobotFeedback.html", "structRobotFeedback" ],
    [ "RobotFeedbackFilter", "classRobotFeedbackFilter.html", "classRobotFeedbackFilter" ],
    [ "RobotFilter", "classRobotFilter.html", "classRobotFilter" ],
    [ "RobotID", "structRobotID.html", "structRobotID" ],
    [ "RobotObservation", "structRobotObservation.html", "structRobotObservation" ],
    [ "RobotOrientationFilter", "classRobotOrientationFilter.html", "classRobotOrientationFilter" ],
    [ "RobotParameterDatabase", "classRobotParameterDatabase.html", "classRobotParameterDatabase" ],
    [ "RobotParameters", "classRobotParameters.html", "classRobotParameters" ],
    [ "RobotPath", "structRobotPath.html", "structRobotPath" ],
    [ "RobotPos", "classRobotPos.html", "classRobotPos" ],
    [ "RobotProperties", "RobotProperties_8hpp.html#structRobotProperties", "RobotProperties_8hpp_structRobotProperties" ],
    [ "RobotsFeedback", "structRobotsFeedback.html", "structRobotsFeedback" ],
    [ "RobotSTP", "structRobotSTP.html", "structRobotSTP" ],
    [ "RobotVel", "classRobotVel.html", "classRobotVel" ],
    [ "RTT_AI_Tests", "classRTT__AI__Tests.html", "classRTT__AI__Tests" ],
    [ "SimpleRandom", "classSimpleRandom.html", "classSimpleRandom" ],
    [ "SimulationError", "Feedback_8hpp.html#structSimulationError", "Feedback_8hpp_structSimulationError" ],
    [ "SimulatorNetworkConfiguration", "SimulatorManager_8hpp.html#structSimulatorNetworkConfiguration", "SimulatorManager_8hpp_structSimulatorNetworkConfiguration" ],
    [ "SingleRobotFeedbackFilter", "classSingleRobotFeedbackFilter.html", "classSingleRobotFeedbackFilter" ],
    [ "SkillInfo", "StateMachineTest_8cpp.html#structSkillInfo", null ],
    [ "TeamRobotID", "structTeamRobotID.html", "structTeamRobotID" ],
    [ "TestHeader", "LoggingTest_8cpp.html#structTestHeader", "LoggingTest_8cpp_structTestHeader" ],
    [ "TestSkill", "classTestSkill.html", "classTestSkill" ],
    [ "Time", "classTime.html", "classTime" ],
    [ "TwoTeamRobotParameters", "structTwoTeamRobotParameters.html", "structTwoTeamRobotParameters" ],
    [ "vec2d", "CircularBufferTest_8cpp.html#structvec2d", "CircularBufferTest_8cpp_structvec2d" ],
    [ "VisionFilter", "classVisionFilter.html", "classVisionFilter" ],
    [ "World", "structWorld.html", "structWorld" ],
    [ "WorldFilter", "classWorldFilter.html", "classWorldFilter" ],
    [ "WorldStates", "structWorldStates.html", "structWorldStates" ]
];