FROM python:3.9-slim

# Install system dependencies
RUN apt-get update && \
    apt-get install -y libzmq3-dev build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install pyzmq protobuf

# Create working directory
WORKDIR /app

# Copy the Python script and proto files
COPY roboteam_ai/src/rl/src/zmq_teleport_robots_server.py /app/
COPY /roboteam_networking/ /app/roboteam_networking/

# Run the script
CMD ["python", "zmq_teleport_robots_server.py"]