// AUTOGENERATED. Run generator/main.py to regenerate
// Warning : Check the unicode table before assigning a byte, to make sure that the byte isn't used for anything special : https://unicode-table.com/
// For example, don't use the following bytes
// 0b00000000 : The null-terminator, used to signal the end of strings / arrays / etc.
// 0b00001010 : The byte for newline, used for line termination.

#ifndef __BASETYPES_H
#define __BASETYPES_H

#include <stdint.h>

#define LOCAL_REM_VERSION 6

#define PACKET_TYPE_R_E_M__ROBOT_COMMAND                             0b00001111 // 15 
#define PACKET_SIZE_R_E_M__ROBOT_COMMAND                             12
#define PACKET_RANGE_R_E_M__ROBOT_COMMAND_RHO_MIN                    0.
#define PACKET_RANGE_R_E_M__ROBOT_COMMAND_RHO_MAX                    8.
#define PACKET_RANGE_R_E_M__ROBOT_COMMAND_RHO_N_BITS                 16
#define PACKET_RANGE_R_E_M__ROBOT_COMMAND_THETA_MIN                  -3.1415926535897931
#define PACKET_RANGE_R_E_M__ROBOT_COMMAND_THETA_MAX                  3.1415926535897931
#define PACKET_RANGE_R_E_M__ROBOT_COMMAND_THETA_N_BITS               16
#define PACKET_RANGE_R_E_M__ROBOT_COMMAND_ANGLE_MIN                  -3.1415926535897931
#define PACKET_RANGE_R_E_M__ROBOT_COMMAND_ANGLE_MAX                  3.1415926535897931
#define PACKET_RANGE_R_E_M__ROBOT_COMMAND_ANGLE_N_BITS               16
#define PACKET_RANGE_R_E_M__ROBOT_COMMAND_CAMERA_ANGLE_MIN           -3.1415926535897931
#define PACKET_RANGE_R_E_M__ROBOT_COMMAND_CAMERA_ANGLE_MAX           3.1415926535897931
#define PACKET_RANGE_R_E_M__ROBOT_COMMAND_CAMERA_ANGLE_N_BITS        16
#define PACKET_RANGE_R_E_M__ROBOT_COMMAND_DRIBBLER_MIN               0.
#define PACKET_RANGE_R_E_M__ROBOT_COMMAND_DRIBBLER_MAX               1.
#define PACKET_RANGE_R_E_M__ROBOT_COMMAND_DRIBBLER_N_BITS            3
#define PACKET_RANGE_R_E_M__ROBOT_COMMAND_KICK_CHIP_POWER_MIN        0.
#define PACKET_RANGE_R_E_M__ROBOT_COMMAND_KICK_CHIP_POWER_MAX        6.5
#define PACKET_RANGE_R_E_M__ROBOT_COMMAND_KICK_CHIP_POWER_N_BITS     3

#define PACKET_TYPE_R_E_M__ROBOT_FEEDBACK                            0b00110011 // 51 
#define PACKET_SIZE_R_E_M__ROBOT_FEEDBACK                            12
#define PACKET_RANGE_R_E_M__ROBOT_FEEDBACK_BALL_POS_MIN              -0.5
#define PACKET_RANGE_R_E_M__ROBOT_FEEDBACK_BALL_POS_MAX              0.5
#define PACKET_RANGE_R_E_M__ROBOT_FEEDBACK_BALL_POS_N_BITS           4
#define PACKET_RANGE_R_E_M__ROBOT_FEEDBACK_RHO_MIN                   0.
#define PACKET_RANGE_R_E_M__ROBOT_FEEDBACK_RHO_MAX                   8.
#define PACKET_RANGE_R_E_M__ROBOT_FEEDBACK_RHO_N_BITS                16
#define PACKET_RANGE_R_E_M__ROBOT_FEEDBACK_THETA_MIN                 -3.1415926535897931
#define PACKET_RANGE_R_E_M__ROBOT_FEEDBACK_THETA_MAX                 3.1415926535897931
#define PACKET_RANGE_R_E_M__ROBOT_FEEDBACK_THETA_N_BITS              16
#define PACKET_RANGE_R_E_M__ROBOT_FEEDBACK_ANGLE_MIN                 -3.1415926535897931
#define PACKET_RANGE_R_E_M__ROBOT_FEEDBACK_ANGLE_MAX                 3.1415926535897931
#define PACKET_RANGE_R_E_M__ROBOT_FEEDBACK_ANGLE_N_BITS              16

#define PACKET_TYPE_R_E_M__ROBOT_STATE_INFO                          0b00111100 // 60 
#define PACKET_SIZE_R_E_M__ROBOT_STATE_INFO                          35
#define PACKET_RANGE_R_E_M__ROBOT_STATE_INFO_XSENS_ACC1_MIN          -50000.
#define PACKET_RANGE_R_E_M__ROBOT_STATE_INFO_XSENS_ACC1_MAX          50000.
#define PACKET_RANGE_R_E_M__ROBOT_STATE_INFO_XSENS_ACC1_N_BITS       32
#define PACKET_RANGE_R_E_M__ROBOT_STATE_INFO_XSENS_ACC2_MIN          -50000.
#define PACKET_RANGE_R_E_M__ROBOT_STATE_INFO_XSENS_ACC2_MAX          50000.
#define PACKET_RANGE_R_E_M__ROBOT_STATE_INFO_XSENS_ACC2_N_BITS       32
#define PACKET_RANGE_R_E_M__ROBOT_STATE_INFO_XSENS_YAW_MIN           -50000.
#define PACKET_RANGE_R_E_M__ROBOT_STATE_INFO_XSENS_YAW_MAX           50000.
#define PACKET_RANGE_R_E_M__ROBOT_STATE_INFO_XSENS_YAW_N_BITS        32
#define PACKET_RANGE_R_E_M__ROBOT_STATE_INFO_RATE_OF_TURN_MIN        -50000.
#define PACKET_RANGE_R_E_M__ROBOT_STATE_INFO_RATE_OF_TURN_MAX        50000.
#define PACKET_RANGE_R_E_M__ROBOT_STATE_INFO_RATE_OF_TURN_N_BITS     32
#define PACKET_RANGE_R_E_M__ROBOT_STATE_INFO_WHEEL_SPEED1_MIN        -50000.
#define PACKET_RANGE_R_E_M__ROBOT_STATE_INFO_WHEEL_SPEED1_MAX        50000.
#define PACKET_RANGE_R_E_M__ROBOT_STATE_INFO_WHEEL_SPEED1_N_BITS     32
#define PACKET_RANGE_R_E_M__ROBOT_STATE_INFO_WHEEL_SPEED2_MIN        -50000.
#define PACKET_RANGE_R_E_M__ROBOT_STATE_INFO_WHEEL_SPEED2_MAX        50000.
#define PACKET_RANGE_R_E_M__ROBOT_STATE_INFO_WHEEL_SPEED2_N_BITS     32
#define PACKET_RANGE_R_E_M__ROBOT_STATE_INFO_WHEEL_SPEED3_MIN        -50000.
#define PACKET_RANGE_R_E_M__ROBOT_STATE_INFO_WHEEL_SPEED3_MAX        50000.
#define PACKET_RANGE_R_E_M__ROBOT_STATE_INFO_WHEEL_SPEED3_N_BITS     32
#define PACKET_RANGE_R_E_M__ROBOT_STATE_INFO_WHEEL_SPEED4_MIN        -50000.
#define PACKET_RANGE_R_E_M__ROBOT_STATE_INFO_WHEEL_SPEED4_MAX        50000.
#define PACKET_RANGE_R_E_M__ROBOT_STATE_INFO_WHEEL_SPEED4_N_BITS     32

#define PACKET_TYPE_R_E_M__ROBOT_BUZZER                              0b01010101 // 85 
#define PACKET_SIZE_R_E_M__ROBOT_BUZZER                              6
#define PACKET_RANGE_R_E_M__ROBOT_BUZZER_DURATION_MIN                0.
#define PACKET_RANGE_R_E_M__ROBOT_BUZZER_DURATION_MAX                5.
#define PACKET_RANGE_R_E_M__ROBOT_BUZZER_DURATION_N_BITS             16

#define PACKET_TYPE_R_E_M__BASESTATION_STATISTICS                    0b01011010 // 90 
#define PACKET_SIZE_R_E_M__BASESTATION_STATISTICS                    34

#define PACKET_TYPE_R_E_M__BASESTATION_GET_STATISTICS                0b01100110 // 102 
#define PACKET_SIZE_R_E_M__BASESTATION_GET_STATISTICS                1

#define PACKET_TYPE_R_E_M__BASESTATION_LOG                           0b01101001 // 105 
#define PACKET_SIZE_R_E_M__BASESTATION_LOG                           1

#define PACKET_TYPE_R_E_M__ROBOT_LOG                                 0b10010110 // 150 
#define PACKET_SIZE_R_E_M__ROBOT_LOG                                 3

#define PACKET_TYPE_R_E_M__BASESTATION_GET_CONFIGURATION             0b10011001 // 153 
#define PACKET_SIZE_R_E_M__BASESTATION_GET_CONFIGURATION             1

#define PACKET_TYPE_R_E_M__BASESTATION_CONFIGURATION                 0b10100101 // 165 
#define PACKET_SIZE_R_E_M__BASESTATION_CONFIGURATION                 2

#define PACKET_TYPE_R_E_M__BASESTATION_SET_CONFIGURATION             0b10101010 // 170 
#define PACKET_SIZE_R_E_M__BASESTATION_SET_CONFIGURATION             2

static uint8_t PACKET_TYPE_TO_SIZE(uint8_t type){
    if(type == PACKET_TYPE_R_E_M__ROBOT_COMMAND                            ) return PACKET_SIZE_R_E_M__ROBOT_COMMAND                            ;
    if(type == PACKET_TYPE_R_E_M__ROBOT_FEEDBACK                           ) return PACKET_SIZE_R_E_M__ROBOT_FEEDBACK                           ;
    if(type == PACKET_TYPE_R_E_M__ROBOT_STATE_INFO                         ) return PACKET_SIZE_R_E_M__ROBOT_STATE_INFO                         ;
    if(type == PACKET_TYPE_R_E_M__ROBOT_BUZZER                             ) return PACKET_SIZE_R_E_M__ROBOT_BUZZER                             ;
    if(type == PACKET_TYPE_R_E_M__BASESTATION_STATISTICS                   ) return PACKET_SIZE_R_E_M__BASESTATION_STATISTICS                   ;
    if(type == PACKET_TYPE_R_E_M__BASESTATION_GET_STATISTICS               ) return PACKET_SIZE_R_E_M__BASESTATION_GET_STATISTICS               ;
    if(type == PACKET_TYPE_R_E_M__BASESTATION_LOG                          ) return PACKET_SIZE_R_E_M__BASESTATION_LOG                          ;
    if(type == PACKET_TYPE_R_E_M__ROBOT_LOG                                ) return PACKET_SIZE_R_E_M__ROBOT_LOG                                ;
    if(type == PACKET_TYPE_R_E_M__BASESTATION_GET_CONFIGURATION            ) return PACKET_SIZE_R_E_M__BASESTATION_GET_CONFIGURATION            ;
    if(type == PACKET_TYPE_R_E_M__BASESTATION_CONFIGURATION                ) return PACKET_SIZE_R_E_M__BASESTATION_CONFIGURATION                ;
    if(type == PACKET_TYPE_R_E_M__BASESTATION_SET_CONFIGURATION            ) return PACKET_SIZE_R_E_M__BASESTATION_SET_CONFIGURATION            ;
    return 0;
}

#endif /*__BASETYPES_H*/