// AUTOGENERATED. Run generator/main.py to regenerate
// Generated on July 04 2021, 22:21:31

/*
[  0   ] [  1   ] [  2   ] [  3   ] [  4   ] [  5   ] [  6   ] [  7   ] [  8   ] [  9   ] [  10  ] [  11  ] [  12  ] [  13  ] [  14  ] [  15  ] [  16  ] [  17  ] [  18  ] [  19  ] [  20  ] [  21  ] [  22  ] [  23  ] [  24  ] [  25  ] [  26  ] [  27  ] [  28  ] [  29  ] [  30  ] [  31  ] [  32  ] [  33  ]
11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- header
-------- 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- id
-------- ----1111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- messageId
-------- -------- 11111111 11111111 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- xsensAcc1
-------- -------- -------- -------- -------- -------- 11111111 11111111 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- xsensAcc2
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- xsensYaw
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- rateOfTurn
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- wheelSpeed1
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 11111111 11111111 -------- -------- -------- -------- -------- -------- -------- -------- wheelSpeed2
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 11111111 11111111 -------- -------- -------- -------- wheelSpeed3
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- 11111111 11111111 11111111 11111111 wheelSpeed4
*/

#ifndef __ROBOT_STATE_INFO_H
#define __ROBOT_STATE_INFO_H

#include <stdbool.h>
#include <stdint.h>
#include "BaseTypes.h"

typedef struct _RobotStateInfoPayload {
    uint8_t payload[PACKET_SIZE_ROBOT_STATE_INFO];
} RobotStateInfoPayload;

typedef struct _RobotStateInfo {
    uint32_t   header              ; // Header byte indicating the type of packet
    uint32_t   id                  ; // Id of the robot 
    uint32_t   messageId           ; // Id of the message
    float      xsensAcc1           ; // xsensAcc1
    float      xsensAcc2           ; // xsensAcc2
    float      xsensYaw            ; // xsensYaw
    float      rateOfTurn          ; // rateOfTurn
    float      wheelSpeed1         ; // wheelSpeed1
    float      wheelSpeed2         ; // wheelSpeed2
    float      wheelSpeed3         ; // wheelSpeed3
    float      wheelSpeed4         ; // wheelSpeed4
} RobotStateInfo;

// ================================ GETTERS ================================
static inline uint32_t RobotStateInfo_get_header(RobotStateInfoPayload *rsip){
    return ((rsip->payload[0]));
}

static inline uint32_t RobotStateInfo_get_id(RobotStateInfoPayload *rsip){
    return ((rsip->payload[1] & 0b11110000) >> 4);
}

static inline uint32_t RobotStateInfo_get_messageId(RobotStateInfoPayload *rsip){
    return ((rsip->payload[1] & 0b00001111));
}

// ================================ SETTERS ================================
static inline void RobotStateInfo_set_header(RobotStateInfoPayload *rsip, uint32_t header){
    rsip->payload[0] = header;
}

static inline void RobotStateInfo_set_id(RobotStateInfoPayload *rsip, uint32_t id){
    rsip->payload[1] = ((id << 4) & 0b11110000) | (payload[1] & 0b00001111);
}

static inline void RobotStateInfo_set_messageId(RobotStateInfoPayload *rsip, uint32_t messageId){
    rsip->payload[1] = (messageId & 0b00001111) | (payload[1] & 0b11110000);
}

// ================================ ENCODE ================================
static inline void encodeRobotStateInfo(RobotStateInfoPayload *rsip, RobotStateInfo *rsi){
    RobotStateInfo_set_header              (rsip, rsi->header);
    RobotStateInfo_set_id                  (rsip, rsi->id);
    RobotStateInfo_set_messageId           (rsip, rsi->messageId);
    RobotStateInfo_set_xsensAcc1           (rsip, rsi->xsensAcc1);
    RobotStateInfo_set_xsensAcc2           (rsip, rsi->xsensAcc2);
    RobotStateInfo_set_xsensYaw            (rsip, rsi->xsensYaw);
    RobotStateInfo_set_rateOfTurn          (rsip, rsi->rateOfTurn);
    RobotStateInfo_set_wheelSpeed1         (rsip, rsi->wheelSpeed1);
    RobotStateInfo_set_wheelSpeed2         (rsip, rsi->wheelSpeed2);
    RobotStateInfo_set_wheelSpeed3         (rsip, rsi->wheelSpeed3);
    RobotStateInfo_set_wheelSpeed4         (rsip, rsi->wheelSpeed4);
}

// ================================ DECODE ================================
static inline void decodeRobotStateInfo(RobotStateInfo *rsi, RobotStateInfoPayload *rsip){
    rsi->header          = RobotStateInfo_get_header(rsip);
    rsi->id              = RobotStateInfo_get_id(rsip);
    rsi->messageId       = RobotStateInfo_get_messageId(rsip);
    rsi->xsensAcc1       = RobotStateInfo_get_xsensAcc1(rsip);
    rsi->xsensAcc2       = RobotStateInfo_get_xsensAcc2(rsip);
    rsi->xsensYaw        = RobotStateInfo_get_xsensYaw(rsip);
    rsi->rateOfTurn      = RobotStateInfo_get_rateOfTurn(rsip);
    rsi->wheelSpeed1     = RobotStateInfo_get_wheelSpeed1(rsip);
    rsi->wheelSpeed2     = RobotStateInfo_get_wheelSpeed2(rsip);
    rsi->wheelSpeed3     = RobotStateInfo_get_wheelSpeed3(rsip);
    rsi->wheelSpeed4     = RobotStateInfo_get_wheelSpeed4(rsip);
}

#endif /*__ROBOT_STATE_INFO_H*/
