// AUTOGENERATED. Run generator/main.py to regenerate
/*
[  0   ] [  1   ] [  2   ] [  3   ] [  4   ] [  5   ] [  6   ] [  7   ] [  8   ] [  9   ] [  10  ] [  11  ] [  12  ] [  13  ] [  14  ] [  15  ] [  16  ] [  17  ] [  18  ] [  19  ] [  20  ] [  21  ] [  22  ] [  23  ] [  24  ] [  25  ] [  26  ] [  27  ] [  28  ] [  29  ] [  30  ] [  31  ] [  32  ] [  33  ] [  34  ] [  35  ] [  36  ] [  37  ] [  38  ] [  39  ] [  40  ] [  41  ] [  42  ] [  43  ] [  44  ] [  45  ] [  46  ]
11111111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- header
-------- 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- remVersion
-------- ----1111 -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- id
-------- -------- 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- messageId
-------- -------- ----1111 11111111 11111111 11111111 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- xsensAcc1
-------- -------- -------- -------- -------- -------- ----1111 11111111 11111111 11111111 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- xsensAcc2
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ----1111 11111111 11111111 11111111 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- xsensYaw
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ----1111 11111111 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- rateOfTurn
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ----1111 11111111 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- wheelSpeed1
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ----1111 11111111 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- wheelSpeed2
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ----1111 11111111 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- wheelSpeed3
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ----1111 11111111 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- wheelSpeed4
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ----1111 11111111 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- dribbleSpeed
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ----1111 11111111 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- filteredDribbleSpeed
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ----1111 11111111 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- dribblespeedBeforeGotBall
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ----1111 11111111 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- bodyXIntegral
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ----1111 11111111 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- bodyYIntegral
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ----1111 11111111 1111---- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- bodyWIntegral
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ----1111 11111111 1111---- -------- -------- -------- -------- -------- -------- -------- -------- bodyYawIntegral
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ----1111 11111111 1111---- -------- -------- -------- -------- -------- -------- wheel1Integral
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ----1111 11111111 1111---- -------- -------- -------- -------- wheel2Integral
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ----1111 11111111 1111---- -------- -------- wheel3Integral
-------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- -------- ----1111 11111111 1111---- wheel4Integral
*/

#ifndef __REM_ROBOT_STATE_INFO_H
#define __REM_ROBOT_STATE_INFO_H

#include <stdbool.h>
#include <stdint.h>
#include "REM_BaseTypes.h"

typedef struct _REM_RobotStateInfoPayload {
    uint8_t payload[PACKET_SIZE_REM_ROBOT_STATE_INFO];
} REM_RobotStateInfoPayload;

typedef struct _REM_RobotStateInfo {
    uint32_t   header              ; // integer [0, 255]             Header byte indicating the type of packet
    uint32_t   remVersion          ; // integer [0, 15]              Version of roboteam_embedded_messages
    uint32_t   id                  ; // integer [0, 15]              Id of the robot 
    uint32_t   messageId           ; // integer [0, 15]              Id of the message
    float      xsensAcc1           ; // float   [-50000.000, 50000.000] xsensAcc1
    float      xsensAcc2           ; // float   [-50000.000, 50000.000] xsensAcc2
    float      xsensYaw            ; // float   [-50000.000, 50000.000] xsensYaw
    float      rateOfTurn          ; // float   [-20.000, 20.000]    rateOfTurn
    float      wheelSpeed1         ; // float   [-1000.000, 1000.000] wheelSpeed1
    float      wheelSpeed2         ; // float   [-1000.000, 1000.000] wheelSpeed2
    float      wheelSpeed3         ; // float   [-1000.000, 1000.000] wheelSpeed3
    float      wheelSpeed4         ; // float   [-1000.000, 1000.000] wheelSpeed4
    float      dribbleSpeed        ; // float   [0.000, 5000.000]    dribblerSpeed
    float      filteredDribbleSpeed; // float   [0.000, 5000.000]    filtered dribblerSpeed
    float      dribblespeedBeforeGotBall; // float   [0.000, 5000.000]    dribblerSpeed at at the time dribbler thinks it got the ball
    float      bodyXIntegral       ; // float   [-5000.000, 5000.000] Integral value from the PID for body_x
    float      bodyYIntegral       ; // float   [-5000.000, 5000.000] Integral value from the PID for body_y
    float      bodyWIntegral       ; // float   [-5000.000, 5000.000] Integral value from the PID for body_w
    float      bodyYawIntegral     ; // float   [-5000.000, 5000.000] Integral value from the PID for body_Yaw
    float      wheel1Integral      ; // float   [-5000.000, 5000.000] Integral value from the PID for Wheel_1
    float      wheel2Integral      ; // float   [-5000.000, 5000.000] Integral value from the PID for Wheel_2
    float      wheel3Integral      ; // float   [-5000.000, 5000.000] Integral value from the PID for Wheel_3
    float      wheel4Integral      ; // float   [-5000.000, 5000.000] Integral value from the PID for Wheel_4
} REM_RobotStateInfo;

// ================================ GETTERS ================================
static inline uint32_t REM_RobotStateInfo_get_header(REM_RobotStateInfoPayload *remrsip){
    return ((remrsip->payload[0]));
}

static inline uint32_t REM_RobotStateInfo_get_remVersion(REM_RobotStateInfoPayload *remrsip){
    return ((remrsip->payload[1] & 0b11110000) >> 4);
}

static inline uint32_t REM_RobotStateInfo_get_id(REM_RobotStateInfoPayload *remrsip){
    return ((remrsip->payload[1] & 0b00001111));
}

static inline uint32_t REM_RobotStateInfo_get_messageId(REM_RobotStateInfoPayload *remrsip){
    return ((remrsip->payload[2] & 0b11110000) >> 4);
}

static inline float REM_RobotStateInfo_get_xsensAcc1(REM_RobotStateInfoPayload *remrsip){
    uint32_t _xsensAcc1 = ((remrsip->payload[2] & 0b00001111) << 28) | ((remrsip->payload[3]) << 20) | ((remrsip->payload[4]) << 12) | ((remrsip->payload[5]) << 4) | ((remrsip->payload[6] & 0b11110000) >> 4);
    return (_xsensAcc1 * 0.0000232830643708) + -50000.0000000000000000;
}

static inline float REM_RobotStateInfo_get_xsensAcc2(REM_RobotStateInfoPayload *remrsip){
    uint32_t _xsensAcc2 = ((remrsip->payload[6] & 0b00001111) << 28) | ((remrsip->payload[7]) << 20) | ((remrsip->payload[8]) << 12) | ((remrsip->payload[9]) << 4) | ((remrsip->payload[10] & 0b11110000) >> 4);
    return (_xsensAcc2 * 0.0000232830643708) + -50000.0000000000000000;
}

static inline float REM_RobotStateInfo_get_xsensYaw(REM_RobotStateInfoPayload *remrsip){
    uint32_t _xsensYaw = ((remrsip->payload[10] & 0b00001111) << 28) | ((remrsip->payload[11]) << 20) | ((remrsip->payload[12]) << 12) | ((remrsip->payload[13]) << 4) | ((remrsip->payload[14] & 0b11110000) >> 4);
    return (_xsensYaw * 0.0000232830643708) + -50000.0000000000000000;
}

static inline float REM_RobotStateInfo_get_rateOfTurn(REM_RobotStateInfoPayload *remrsip){
    uint32_t _rateOfTurn = ((remrsip->payload[14] & 0b00001111) << 12) | ((remrsip->payload[15]) << 4) | ((remrsip->payload[16] & 0b11110000) >> 4);
    return (_rateOfTurn * 0.0006103608758679) + -20.0000000000000000;
}

static inline float REM_RobotStateInfo_get_wheelSpeed1(REM_RobotStateInfoPayload *remrsip){
    uint32_t _wheelSpeed1 = ((remrsip->payload[16] & 0b00001111) << 12) | ((remrsip->payload[17]) << 4) | ((remrsip->payload[18] & 0b11110000) >> 4);
    return (_wheelSpeed1 * 0.0305180437933928) + -1000.0000000000000000;
}

static inline float REM_RobotStateInfo_get_wheelSpeed2(REM_RobotStateInfoPayload *remrsip){
    uint32_t _wheelSpeed2 = ((remrsip->payload[18] & 0b00001111) << 12) | ((remrsip->payload[19]) << 4) | ((remrsip->payload[20] & 0b11110000) >> 4);
    return (_wheelSpeed2 * 0.0305180437933928) + -1000.0000000000000000;
}

static inline float REM_RobotStateInfo_get_wheelSpeed3(REM_RobotStateInfoPayload *remrsip){
    uint32_t _wheelSpeed3 = ((remrsip->payload[20] & 0b00001111) << 12) | ((remrsip->payload[21]) << 4) | ((remrsip->payload[22] & 0b11110000) >> 4);
    return (_wheelSpeed3 * 0.0305180437933928) + -1000.0000000000000000;
}

static inline float REM_RobotStateInfo_get_wheelSpeed4(REM_RobotStateInfoPayload *remrsip){
    uint32_t _wheelSpeed4 = ((remrsip->payload[22] & 0b00001111) << 12) | ((remrsip->payload[23]) << 4) | ((remrsip->payload[24] & 0b11110000) >> 4);
    return (_wheelSpeed4 * 0.0305180437933928) + -1000.0000000000000000;
}

static inline float REM_RobotStateInfo_get_dribbleSpeed(REM_RobotStateInfoPayload *remrsip){
    uint32_t _dribbleSpeed = ((remrsip->payload[24] & 0b00001111) << 12) | ((remrsip->payload[25]) << 4) | ((remrsip->payload[26] & 0b11110000) >> 4);
    return (_dribbleSpeed * 0.0762951094834821) + 0.0000000000000000;
}

static inline float REM_RobotStateInfo_get_filteredDribbleSpeed(REM_RobotStateInfoPayload *remrsip){
    uint32_t _filteredDribbleSpeed = ((remrsip->payload[26] & 0b00001111) << 12) | ((remrsip->payload[27]) << 4) | ((remrsip->payload[28] & 0b11110000) >> 4);
    return (_filteredDribbleSpeed * 0.0762951094834821) + 0.0000000000000000;
}

static inline float REM_RobotStateInfo_get_dribblespeedBeforeGotBall(REM_RobotStateInfoPayload *remrsip){
    uint32_t _dribblespeedBeforeGotBall = ((remrsip->payload[28] & 0b00001111) << 12) | ((remrsip->payload[29]) << 4) | ((remrsip->payload[30] & 0b11110000) >> 4);
    return (_dribblespeedBeforeGotBall * 0.0762951094834821) + 0.0000000000000000;
}

static inline float REM_RobotStateInfo_get_bodyXIntegral(REM_RobotStateInfoPayload *remrsip){
    uint32_t _bodyXIntegral = ((remrsip->payload[30] & 0b00001111) << 12) | ((remrsip->payload[31]) << 4) | ((remrsip->payload[32] & 0b11110000) >> 4);
    return (_bodyXIntegral * 0.1525902189669642) + -5000.0000000000000000;
}

static inline float REM_RobotStateInfo_get_bodyYIntegral(REM_RobotStateInfoPayload *remrsip){
    uint32_t _bodyYIntegral = ((remrsip->payload[32] & 0b00001111) << 12) | ((remrsip->payload[33]) << 4) | ((remrsip->payload[34] & 0b11110000) >> 4);
    return (_bodyYIntegral * 0.1525902189669642) + -5000.0000000000000000;
}

static inline float REM_RobotStateInfo_get_bodyWIntegral(REM_RobotStateInfoPayload *remrsip){
    uint32_t _bodyWIntegral = ((remrsip->payload[34] & 0b00001111) << 12) | ((remrsip->payload[35]) << 4) | ((remrsip->payload[36] & 0b11110000) >> 4);
    return (_bodyWIntegral * 0.1525902189669642) + -5000.0000000000000000;
}

static inline float REM_RobotStateInfo_get_bodyYawIntegral(REM_RobotStateInfoPayload *remrsip){
    uint32_t _bodyYawIntegral = ((remrsip->payload[36] & 0b00001111) << 12) | ((remrsip->payload[37]) << 4) | ((remrsip->payload[38] & 0b11110000) >> 4);
    return (_bodyYawIntegral * 0.1525902189669642) + -5000.0000000000000000;
}

static inline float REM_RobotStateInfo_get_wheel1Integral(REM_RobotStateInfoPayload *remrsip){
    uint32_t _wheel1Integral = ((remrsip->payload[38] & 0b00001111) << 12) | ((remrsip->payload[39]) << 4) | ((remrsip->payload[40] & 0b11110000) >> 4);
    return (_wheel1Integral * 0.1525902189669642) + -5000.0000000000000000;
}

static inline float REM_RobotStateInfo_get_wheel2Integral(REM_RobotStateInfoPayload *remrsip){
    uint32_t _wheel2Integral = ((remrsip->payload[40] & 0b00001111) << 12) | ((remrsip->payload[41]) << 4) | ((remrsip->payload[42] & 0b11110000) >> 4);
    return (_wheel2Integral * 0.1525902189669642) + -5000.0000000000000000;
}

static inline float REM_RobotStateInfo_get_wheel3Integral(REM_RobotStateInfoPayload *remrsip){
    uint32_t _wheel3Integral = ((remrsip->payload[42] & 0b00001111) << 12) | ((remrsip->payload[43]) << 4) | ((remrsip->payload[44] & 0b11110000) >> 4);
    return (_wheel3Integral * 0.1525902189669642) + -5000.0000000000000000;
}

static inline float REM_RobotStateInfo_get_wheel4Integral(REM_RobotStateInfoPayload *remrsip){
    uint32_t _wheel4Integral = ((remrsip->payload[44] & 0b00001111) << 12) | ((remrsip->payload[45]) << 4) | ((remrsip->payload[46] & 0b11110000) >> 4);
    return (_wheel4Integral * 0.1525902189669642) + -5000.0000000000000000;
}

// ================================ SETTERS ================================
static inline void REM_RobotStateInfo_set_header(REM_RobotStateInfoPayload *remrsip, uint32_t header){
    remrsip->payload[0] = header;
}

static inline void REM_RobotStateInfo_set_remVersion(REM_RobotStateInfoPayload *remrsip, uint32_t remVersion){
    remrsip->payload[1] = ((remVersion << 4) & 0b11110000) | (remrsip->payload[1] & 0b00001111);
}

static inline void REM_RobotStateInfo_set_id(REM_RobotStateInfoPayload *remrsip, uint32_t id){
    remrsip->payload[1] = (id & 0b00001111) | (remrsip->payload[1] & 0b11110000);
}

static inline void REM_RobotStateInfo_set_messageId(REM_RobotStateInfoPayload *remrsip, uint32_t messageId){
    remrsip->payload[2] = ((messageId << 4) & 0b11110000) | (remrsip->payload[2] & 0b00001111);
}

static inline void REM_RobotStateInfo_set_xsensAcc1(REM_RobotStateInfoPayload *remrsip, float xsensAcc1){
    uint32_t _xsensAcc1 = (uint32_t)((xsensAcc1 +50000.0000000000000000) / 0.0000232830643708);
    remrsip->payload[2] = ((_xsensAcc1 >> 28) & 0b00001111) | (remrsip->payload[2] & 0b11110000);
    remrsip->payload[3] = (_xsensAcc1 >> 20);
    remrsip->payload[4] = (_xsensAcc1 >> 12);
    remrsip->payload[5] = (_xsensAcc1 >> 4);
    remrsip->payload[6] = ((_xsensAcc1 << 4) & 0b11110000) | (remrsip->payload[6] & 0b00001111);
}

static inline void REM_RobotStateInfo_set_xsensAcc2(REM_RobotStateInfoPayload *remrsip, float xsensAcc2){
    uint32_t _xsensAcc2 = (uint32_t)((xsensAcc2 +50000.0000000000000000) / 0.0000232830643708);
    remrsip->payload[6] = ((_xsensAcc2 >> 28) & 0b00001111) | (remrsip->payload[6] & 0b11110000);
    remrsip->payload[7] = (_xsensAcc2 >> 20);
    remrsip->payload[8] = (_xsensAcc2 >> 12);
    remrsip->payload[9] = (_xsensAcc2 >> 4);
    remrsip->payload[10] = ((_xsensAcc2 << 4) & 0b11110000) | (remrsip->payload[10] & 0b00001111);
}

static inline void REM_RobotStateInfo_set_xsensYaw(REM_RobotStateInfoPayload *remrsip, float xsensYaw){
    uint32_t _xsensYaw = (uint32_t)((xsensYaw +50000.0000000000000000) / 0.0000232830643708);
    remrsip->payload[10] = ((_xsensYaw >> 28) & 0b00001111) | (remrsip->payload[10] & 0b11110000);
    remrsip->payload[11] = (_xsensYaw >> 20);
    remrsip->payload[12] = (_xsensYaw >> 12);
    remrsip->payload[13] = (_xsensYaw >> 4);
    remrsip->payload[14] = ((_xsensYaw << 4) & 0b11110000) | (remrsip->payload[14] & 0b00001111);
}

static inline void REM_RobotStateInfo_set_rateOfTurn(REM_RobotStateInfoPayload *remrsip, float rateOfTurn){
    uint32_t _rateOfTurn = (uint32_t)((rateOfTurn +20.0000000000000000) / 0.0006103608758679);
    remrsip->payload[14] = ((_rateOfTurn >> 12) & 0b00001111) | (remrsip->payload[14] & 0b11110000);
    remrsip->payload[15] = (_rateOfTurn >> 4);
    remrsip->payload[16] = ((_rateOfTurn << 4) & 0b11110000) | (remrsip->payload[16] & 0b00001111);
}

static inline void REM_RobotStateInfo_set_wheelSpeed1(REM_RobotStateInfoPayload *remrsip, float wheelSpeed1){
    uint32_t _wheelSpeed1 = (uint32_t)((wheelSpeed1 +1000.0000000000000000) / 0.0305180437933928);
    remrsip->payload[16] = ((_wheelSpeed1 >> 12) & 0b00001111) | (remrsip->payload[16] & 0b11110000);
    remrsip->payload[17] = (_wheelSpeed1 >> 4);
    remrsip->payload[18] = ((_wheelSpeed1 << 4) & 0b11110000) | (remrsip->payload[18] & 0b00001111);
}

static inline void REM_RobotStateInfo_set_wheelSpeed2(REM_RobotStateInfoPayload *remrsip, float wheelSpeed2){
    uint32_t _wheelSpeed2 = (uint32_t)((wheelSpeed2 +1000.0000000000000000) / 0.0305180437933928);
    remrsip->payload[18] = ((_wheelSpeed2 >> 12) & 0b00001111) | (remrsip->payload[18] & 0b11110000);
    remrsip->payload[19] = (_wheelSpeed2 >> 4);
    remrsip->payload[20] = ((_wheelSpeed2 << 4) & 0b11110000) | (remrsip->payload[20] & 0b00001111);
}

static inline void REM_RobotStateInfo_set_wheelSpeed3(REM_RobotStateInfoPayload *remrsip, float wheelSpeed3){
    uint32_t _wheelSpeed3 = (uint32_t)((wheelSpeed3 +1000.0000000000000000) / 0.0305180437933928);
    remrsip->payload[20] = ((_wheelSpeed3 >> 12) & 0b00001111) | (remrsip->payload[20] & 0b11110000);
    remrsip->payload[21] = (_wheelSpeed3 >> 4);
    remrsip->payload[22] = ((_wheelSpeed3 << 4) & 0b11110000) | (remrsip->payload[22] & 0b00001111);
}

static inline void REM_RobotStateInfo_set_wheelSpeed4(REM_RobotStateInfoPayload *remrsip, float wheelSpeed4){
    uint32_t _wheelSpeed4 = (uint32_t)((wheelSpeed4 +1000.0000000000000000) / 0.0305180437933928);
    remrsip->payload[22] = ((_wheelSpeed4 >> 12) & 0b00001111) | (remrsip->payload[22] & 0b11110000);
    remrsip->payload[23] = (_wheelSpeed4 >> 4);
    remrsip->payload[24] = ((_wheelSpeed4 << 4) & 0b11110000) | (remrsip->payload[24] & 0b00001111);
}

static inline void REM_RobotStateInfo_set_dribbleSpeed(REM_RobotStateInfoPayload *remrsip, float dribbleSpeed){
    uint32_t _dribbleSpeed = (uint32_t)(dribbleSpeed / 0.0762951094834821);
    remrsip->payload[24] = ((_dribbleSpeed >> 12) & 0b00001111) | (remrsip->payload[24] & 0b11110000);
    remrsip->payload[25] = (_dribbleSpeed >> 4);
    remrsip->payload[26] = ((_dribbleSpeed << 4) & 0b11110000) | (remrsip->payload[26] & 0b00001111);
}

static inline void REM_RobotStateInfo_set_filteredDribbleSpeed(REM_RobotStateInfoPayload *remrsip, float filteredDribbleSpeed){
    uint32_t _filteredDribbleSpeed = (uint32_t)(filteredDribbleSpeed / 0.0762951094834821);
    remrsip->payload[26] = ((_filteredDribbleSpeed >> 12) & 0b00001111) | (remrsip->payload[26] & 0b11110000);
    remrsip->payload[27] = (_filteredDribbleSpeed >> 4);
    remrsip->payload[28] = ((_filteredDribbleSpeed << 4) & 0b11110000) | (remrsip->payload[28] & 0b00001111);
}

static inline void REM_RobotStateInfo_set_dribblespeedBeforeGotBall(REM_RobotStateInfoPayload *remrsip, float dribblespeedBeforeGotBall){
    uint32_t _dribblespeedBeforeGotBall = (uint32_t)(dribblespeedBeforeGotBall / 0.0762951094834821);
    remrsip->payload[28] = ((_dribblespeedBeforeGotBall >> 12) & 0b00001111) | (remrsip->payload[28] & 0b11110000);
    remrsip->payload[29] = (_dribblespeedBeforeGotBall >> 4);
    remrsip->payload[30] = ((_dribblespeedBeforeGotBall << 4) & 0b11110000) | (remrsip->payload[30] & 0b00001111);
}

static inline void REM_RobotStateInfo_set_bodyXIntegral(REM_RobotStateInfoPayload *remrsip, float bodyXIntegral){
    uint32_t _bodyXIntegral = (uint32_t)((bodyXIntegral +5000.0000000000000000) / 0.1525902189669642);
    remrsip->payload[30] = ((_bodyXIntegral >> 12) & 0b00001111) | (remrsip->payload[30] & 0b11110000);
    remrsip->payload[31] = (_bodyXIntegral >> 4);
    remrsip->payload[32] = ((_bodyXIntegral << 4) & 0b11110000) | (remrsip->payload[32] & 0b00001111);
}

static inline void REM_RobotStateInfo_set_bodyYIntegral(REM_RobotStateInfoPayload *remrsip, float bodyYIntegral){
    uint32_t _bodyYIntegral = (uint32_t)((bodyYIntegral +5000.0000000000000000) / 0.1525902189669642);
    remrsip->payload[32] = ((_bodyYIntegral >> 12) & 0b00001111) | (remrsip->payload[32] & 0b11110000);
    remrsip->payload[33] = (_bodyYIntegral >> 4);
    remrsip->payload[34] = ((_bodyYIntegral << 4) & 0b11110000) | (remrsip->payload[34] & 0b00001111);
}

static inline void REM_RobotStateInfo_set_bodyWIntegral(REM_RobotStateInfoPayload *remrsip, float bodyWIntegral){
    uint32_t _bodyWIntegral = (uint32_t)((bodyWIntegral +5000.0000000000000000) / 0.1525902189669642);
    remrsip->payload[34] = ((_bodyWIntegral >> 12) & 0b00001111) | (remrsip->payload[34] & 0b11110000);
    remrsip->payload[35] = (_bodyWIntegral >> 4);
    remrsip->payload[36] = ((_bodyWIntegral << 4) & 0b11110000) | (remrsip->payload[36] & 0b00001111);
}

static inline void REM_RobotStateInfo_set_bodyYawIntegral(REM_RobotStateInfoPayload *remrsip, float bodyYawIntegral){
    uint32_t _bodyYawIntegral = (uint32_t)((bodyYawIntegral +5000.0000000000000000) / 0.1525902189669642);
    remrsip->payload[36] = ((_bodyYawIntegral >> 12) & 0b00001111) | (remrsip->payload[36] & 0b11110000);
    remrsip->payload[37] = (_bodyYawIntegral >> 4);
    remrsip->payload[38] = ((_bodyYawIntegral << 4) & 0b11110000) | (remrsip->payload[38] & 0b00001111);
}

static inline void REM_RobotStateInfo_set_wheel1Integral(REM_RobotStateInfoPayload *remrsip, float wheel1Integral){
    uint32_t _wheel1Integral = (uint32_t)((wheel1Integral +5000.0000000000000000) / 0.1525902189669642);
    remrsip->payload[38] = ((_wheel1Integral >> 12) & 0b00001111) | (remrsip->payload[38] & 0b11110000);
    remrsip->payload[39] = (_wheel1Integral >> 4);
    remrsip->payload[40] = ((_wheel1Integral << 4) & 0b11110000) | (remrsip->payload[40] & 0b00001111);
}

static inline void REM_RobotStateInfo_set_wheel2Integral(REM_RobotStateInfoPayload *remrsip, float wheel2Integral){
    uint32_t _wheel2Integral = (uint32_t)((wheel2Integral +5000.0000000000000000) / 0.1525902189669642);
    remrsip->payload[40] = ((_wheel2Integral >> 12) & 0b00001111) | (remrsip->payload[40] & 0b11110000);
    remrsip->payload[41] = (_wheel2Integral >> 4);
    remrsip->payload[42] = ((_wheel2Integral << 4) & 0b11110000) | (remrsip->payload[42] & 0b00001111);
}

static inline void REM_RobotStateInfo_set_wheel3Integral(REM_RobotStateInfoPayload *remrsip, float wheel3Integral){
    uint32_t _wheel3Integral = (uint32_t)((wheel3Integral +5000.0000000000000000) / 0.1525902189669642);
    remrsip->payload[42] = ((_wheel3Integral >> 12) & 0b00001111) | (remrsip->payload[42] & 0b11110000);
    remrsip->payload[43] = (_wheel3Integral >> 4);
    remrsip->payload[44] = ((_wheel3Integral << 4) & 0b11110000) | (remrsip->payload[44] & 0b00001111);
}

static inline void REM_RobotStateInfo_set_wheel4Integral(REM_RobotStateInfoPayload *remrsip, float wheel4Integral){
    uint32_t _wheel4Integral = (uint32_t)((wheel4Integral +5000.0000000000000000) / 0.1525902189669642);
    remrsip->payload[44] = ((_wheel4Integral >> 12) & 0b00001111) | (remrsip->payload[44] & 0b11110000);
    remrsip->payload[45] = (_wheel4Integral >> 4);
    remrsip->payload[46] = ((_wheel4Integral << 4) & 0b11110000) | (remrsip->payload[46] & 0b00001111);
}

// ================================ ENCODE ================================
static inline void encodeREM_RobotStateInfo(REM_RobotStateInfoPayload *remrsip, REM_RobotStateInfo *remrsi){
    REM_RobotStateInfo_set_header              (remrsip, remrsi->header);
    REM_RobotStateInfo_set_remVersion          (remrsip, remrsi->remVersion);
    REM_RobotStateInfo_set_id                  (remrsip, remrsi->id);
    REM_RobotStateInfo_set_messageId           (remrsip, remrsi->messageId);
    REM_RobotStateInfo_set_xsensAcc1           (remrsip, remrsi->xsensAcc1);
    REM_RobotStateInfo_set_xsensAcc2           (remrsip, remrsi->xsensAcc2);
    REM_RobotStateInfo_set_xsensYaw            (remrsip, remrsi->xsensYaw);
    REM_RobotStateInfo_set_rateOfTurn          (remrsip, remrsi->rateOfTurn);
    REM_RobotStateInfo_set_wheelSpeed1         (remrsip, remrsi->wheelSpeed1);
    REM_RobotStateInfo_set_wheelSpeed2         (remrsip, remrsi->wheelSpeed2);
    REM_RobotStateInfo_set_wheelSpeed3         (remrsip, remrsi->wheelSpeed3);
    REM_RobotStateInfo_set_wheelSpeed4         (remrsip, remrsi->wheelSpeed4);
    REM_RobotStateInfo_set_dribbleSpeed        (remrsip, remrsi->dribbleSpeed);
    REM_RobotStateInfo_set_filteredDribbleSpeed(remrsip, remrsi->filteredDribbleSpeed);
    REM_RobotStateInfo_set_dribblespeedBeforeGotBall(remrsip, remrsi->dribblespeedBeforeGotBall);
    REM_RobotStateInfo_set_bodyXIntegral       (remrsip, remrsi->bodyXIntegral);
    REM_RobotStateInfo_set_bodyYIntegral       (remrsip, remrsi->bodyYIntegral);
    REM_RobotStateInfo_set_bodyWIntegral       (remrsip, remrsi->bodyWIntegral);
    REM_RobotStateInfo_set_bodyYawIntegral     (remrsip, remrsi->bodyYawIntegral);
    REM_RobotStateInfo_set_wheel1Integral      (remrsip, remrsi->wheel1Integral);
    REM_RobotStateInfo_set_wheel2Integral      (remrsip, remrsi->wheel2Integral);
    REM_RobotStateInfo_set_wheel3Integral      (remrsip, remrsi->wheel3Integral);
    REM_RobotStateInfo_set_wheel4Integral      (remrsip, remrsi->wheel4Integral);
}

// ================================ DECODE ================================
static inline void decodeREM_RobotStateInfo(REM_RobotStateInfo *remrsi, REM_RobotStateInfoPayload *remrsip){
    remrsi->header       = REM_RobotStateInfo_get_header(remrsip);
    remrsi->remVersion   = REM_RobotStateInfo_get_remVersion(remrsip);
    remrsi->id           = REM_RobotStateInfo_get_id(remrsip);
    remrsi->messageId    = REM_RobotStateInfo_get_messageId(remrsip);
    remrsi->xsensAcc1    = REM_RobotStateInfo_get_xsensAcc1(remrsip);
    remrsi->xsensAcc2    = REM_RobotStateInfo_get_xsensAcc2(remrsip);
    remrsi->xsensYaw     = REM_RobotStateInfo_get_xsensYaw(remrsip);
    remrsi->rateOfTurn   = REM_RobotStateInfo_get_rateOfTurn(remrsip);
    remrsi->wheelSpeed1  = REM_RobotStateInfo_get_wheelSpeed1(remrsip);
    remrsi->wheelSpeed2  = REM_RobotStateInfo_get_wheelSpeed2(remrsip);
    remrsi->wheelSpeed3  = REM_RobotStateInfo_get_wheelSpeed3(remrsip);
    remrsi->wheelSpeed4  = REM_RobotStateInfo_get_wheelSpeed4(remrsip);
    remrsi->dribbleSpeed = REM_RobotStateInfo_get_dribbleSpeed(remrsip);
    remrsi->filteredDribbleSpeed= REM_RobotStateInfo_get_filteredDribbleSpeed(remrsip);
    remrsi->dribblespeedBeforeGotBall= REM_RobotStateInfo_get_dribblespeedBeforeGotBall(remrsip);
    remrsi->bodyXIntegral= REM_RobotStateInfo_get_bodyXIntegral(remrsip);
    remrsi->bodyYIntegral= REM_RobotStateInfo_get_bodyYIntegral(remrsip);
    remrsi->bodyWIntegral= REM_RobotStateInfo_get_bodyWIntegral(remrsip);
    remrsi->bodyYawIntegral= REM_RobotStateInfo_get_bodyYawIntegral(remrsip);
    remrsi->wheel1Integral= REM_RobotStateInfo_get_wheel1Integral(remrsip);
    remrsi->wheel2Integral= REM_RobotStateInfo_get_wheel2Integral(remrsip);
    remrsi->wheel3Integral= REM_RobotStateInfo_get_wheel3Integral(remrsip);
    remrsi->wheel4Integral= REM_RobotStateInfo_get_wheel4Integral(remrsip);
}

#endif /*__REM_ROBOT_STATE_INFO_H*/
