# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WorldBall.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector2f_pb2 as Vector2f__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fWorldBall.proto\x12\x05proto\x1a\x0eVector2f.proto\"\x80\x01\n\tWorldBall\x12\x0c\n\x04\x61rea\x18\x01 \x01(\r\x12\x1c\n\x03pos\x18\x02 \x01(\x0b\x32\x0f.proto.Vector2f\x12\t\n\x01z\x18\x03 \x01(\x02\x12\x1c\n\x03vel\x18\x04 \x01(\x0b\x32\x0f.proto.Vector2f\x12\r\n\x05z_vel\x18\x05 \x01(\x02\x12\x0f\n\x07visible\x18\x06 \x01(\x08\x62\x06proto3')



_WORLDBALL = DESCRIPTOR.message_types_by_name['WorldBall']
WorldBall = _reflection.GeneratedProtocolMessageType('WorldBall', (_message.Message,), {
  'DESCRIPTOR' : _WORLDBALL,
  '__module__' : 'WorldBall_pb2'
  # @@protoc_insertion_point(class_scope:proto.WorldBall)
  })
_sym_db.RegisterMessage(WorldBall)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WORLDBALL._serialized_start=43
  _WORLDBALL._serialized_end=171
# @@protoc_insertion_point(module_scope)
