FROM python:3.9-slim

# Install system dependencies
RUN apt-get update && \
    apt-get install -y libzmq3-dev build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install pyzmq

# Create working directory
WORKDIR /app

# Copy the Python script from src directory
COPY src/multicast.py /app/

# Run the script
CMD ["python", "multicast.py"]