apiVersion: apps/v1
kind: Deployment
metadata:
  name: roboteam-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roboteam-simulator
  template:
    metadata:
      labels:
        app: roboteam-simulator
    spec:
      containers:
      - name: ssl-game-controller
        ports:
        - containerPort: 8081
        image: robocupssl/ssl-game-controller:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

      - name: roboteam-primary-ai
        image: roboteamtwente/roboteam:kubernetes
        command: ["/bin/sh"]
        args: ["-c", "/home/roboteam/build/release/bin/roboteam_ai --primary-ai"]
        env:
          - name: LD_LIBRARY_PATH
            value: "/home/roboteam/build/release/lib"
        workingDir: /home/roboteam
        ports:
        - containerPort: 12676
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi

      - name: roboteam-observer-sim
        image: roboteamtwente/roboteam:kubernetes
        command: ["/bin/sh"]
        args: ["-c", "/home/roboteam/build/release/bin/roboteam_observer --vision-ip 127.0.0.1 --referee-ip 127.0.0.1 --vision-port 10020 --referee-port 10003 --log"]
        env:
          - name: LD_LIBRARY_PATH
            value: /home/roboteam/build/release/lib
        workingDir: /home/roboteam
        ports:
        - containerPort: 10006
        - containerPort: 10020
        - containerPort: 10003
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi

      - name: roboteam-robothub-sim
        image: roboteamtwente/roboteam:kubernetes
        command: ["/bin/sh"]
        args: ["-c", "/home/roboteam/build/release/bin/roboteam_robothub"]
        env:
          - name: LD_LIBRARY_PATH
            value: /home/roboteam/build/release/lib
        workingDir: /home/roboteam
        ports:
        - containerPort: 10301
        - containerPort: 30011
        - containerPort: 10302
        - containerPort: 30012
        - containerPort: 10300
        - containerPort: 30013
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 500Mi

      - name: roboteam-interface
        image: roboteamtwente/roboteam:kubernetes
        command: ["/bin/sh"]
        args: ["-c", "cd /home/roboteam/roboteam_interface && yarn serve --host 0.0.0.0"]
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 500Mi

      - name: erforce-autoref-sim
        image: roboteamtwente/roboteam:kubernetes
        command: ["/bin/sh"]
        args: ["-c", "cd /home/roboteam/external/autoref/build/bin && ./autoref-cli --vision-port 10020 --tracker-port 10010 --gc-port 10003"]
        ports:
        - containerPort: 10020
        - containerPort: 10003
        - containerPort: 10010
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

      - name: erforce-simulator
        image: roboteamtwente/roboteam:kubernetes
        command: ["/bin/sh"]
        args: 
        - "-c"
        - "/home/roboteam/external/framework/build/bin/simulator-cli -g 2020 --realism Realistic"
        ports:
        - containerPort: 10301
        - containerPort: 30011
        - containerPort: 10302
        - containerPort: 30012
        - containerPort: 10300
        - containerPort: 30013
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 500Mi