name: Publish Docker Image

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: recursive
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push development
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          push: true
          target: development
          tags: tollsimy/roboteam-rl:development
      - 
        name: Build sources from development
        uses: addnab/docker-run-action@v3
        with:
          image: tollsimy/roboteam-rl:development
          options: -v ${{ github.workspace }}:/home/roboteamtwente/
          run: |
            sudo chown -R $(id -u):$(id -g) .
            ./build.sh
      - 
        name: Build and push release from sources
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          target: release
          tags: tollsimy/roboteam-rl:latest