name: GTests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Restored cached build
        id: cache-build-restore
        uses: actions/cache/restore@v3
        with:
          path: .
          key: ${{ runner.os }}-build
      
      - name: Install dependecies
        run: |
            chmod +x ./install_UBUNTU_20_04.sh
            sudo ./install_UBUNTU_20_04.sh
            sudo apt install -y qtcreator qtbase5-dev qt5-qmake cmake
            
      - name: Configure
        run: mkdir build && cd build && cmake ..
        
      - name: Build
        run: cmake --build build --target roboteam_ai_tests -j $(nproc) &&
             cmake --build build --target roboteam_utils_tests -j $(nproc) &&
             cmake --build build --target roboteam_networking_tests -j $(nproc)
             
      - name: Run
        run: ./build/roboteam_ai/roboteam_ai_tests && 
             ./build/roboteam_networking/roboteam_networking_tests &&
             ./build/roboteam_utils/roboteam_utils_tests
      
      - name: Save build
        id: cache-build-save
        uses: actions/cache/save@v3
        with:
          path: .
          key: ${{ steps.cache-build-restore.outputs.cache-primary-key }}
