name: GTests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install gtest
        run: sudo apt-get install libgtest-dev
      - name: Configure
        run: ls ${{ github.workspace }}
