name: GTests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gtest
      run: |
          chmod +x .${{ github.workspace }}/install_UBUNTU_20_04.sh
          sudo .${{ github.workspace }}/install_UBUNTU_20_04.sh
      shell: bash
