name: GTests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependecies
        run: |
            chmod +x ./install_UBUNTU_20_04.sh
            sudo ./install_UBUNTU_20_04.sh
      - name: Configure
        run: mkdir build && cd build && cmake ..
      - name: Build
        run: cmake --build build --target roboteam_ai_tests
        
